import { Product } from '@/types/ecommerce';

export const MOCK_PRODUCTS: Product[] = [
  // --- PANTRY & CONFECTIONERY ---
  {
    id: 'prod-001',
    slug: 'kirkland-unsalted-mixed-nuts-2-5lb',
    gtin: '096619284218',
    name: 'Kirkland Extra Fancy Unsalted Mixed Nuts',
    brand: 'Kirkland Signature',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Premium mix of cashews, almonds, pistachios, and macadamia nuts roasted without salt (2.5 lb / 1.13 kg).',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/kirkland-unsalted-mixed-nuts-2-5lb.avif', altText: 'Kirkland Unsalted Mixed Nuts', isPrimary: true }],
    inStock: true,
    stockQuantity: 50,
    ratingAverage: 4.9,
    reviewCount: 140,
    specifications: [{ label: 'Weight', value: '2.5 lbs (1.13 kg)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    slug: 'kirkland-salted-mixed-nuts-2-5lb',
    gtin: '096619164557',
    name: 'Kirkland Extra Fancy Salted Mixed Nuts',
    brand: 'Kirkland Signature',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Roasted mixed nuts with cashews, almonds, pecans, Brazil nuts, and macadamias lightly salted (2.5 lb / 1.13 kg).',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/kirkland-salted-mixed-nuts-2-5lb-blue.jpg', altText: 'Kirkland Salted Mixed Nuts', isPrimary: true }],
    inStock: true,
    stockQuantity: 40,
    ratingAverage: 4.8,
    reviewCount: 95,
    specifications: [{ label: 'Weight', value: '2.5 lbs (1.13 kg)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    slug: 'lindt-lindor-assorted-truffles-21-2oz',
    gtin: '003746601633',
    name: 'Lindt LINDOR Assorted Chocolate Truffles',
    brand: 'Lindt',
    categorySlug: 'pantry',
    subCategorySlug: 'confectionery',
    description: 'Irresistibly smooth assorted chocolate truffles including milk, dark, white, and extra dark (21.2 oz / 600g).',
    price: 3500,
    currency: 'BIRR',
    images: [{ url: '/products/lindt-lindor-assorted-truffles-21-2oz.avif', altText: 'Lindt Lindor Assorted Truffles', isPrimary: true }],
    inStock: true,
    stockQuantity: 30,
    ratingAverage: 4.9,
    reviewCount: 210,
    specifications: [{ label: 'Weight', value: '21.2 oz (600 g)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    slug: 'nutella-hazelnut-spread-2-pack',
    gtin: '009800895200',
    name: 'Nutella Hazelnut Spread with Cocoa (2 Pack)',
    brand: 'Nutella',
    categorySlug: 'pantry',
    subCategorySlug: 'spreads',
    description: 'Original rich hazelnut and cocoa spread bundle (Two 33.5 oz / 950g jars).',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/nutella-hazelnut-spread-2-pack.avif', altText: 'Nutella Hazelnut Spread Twin Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 25,
    ratingAverage: 5.0,
    reviewCount: 310,
    specifications: [{ label: 'Net Weight', value: '67 oz Total (2 x 33.5 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    slug: 'mayorga-organic-chia-seeds-3lb',
    gtin: '089708000215',
    name: 'Mayorga Organics BIRRA Chia Seeds',
    brand: 'Mayorga Organics',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Small farmer direct organic non-GMO gluten-free chia seeds (3 lb / 1.36 kg).',
    price: 5790,
    currency: 'BIRR',
    images: [{ url: '/products/mayorga-organic-chia-seeds-3lb.jpg', altText: 'Mayorga Organics Chia Seeds', isPrimary: true }],
    inStock: true,
    stockQuantity: 60,
    ratingAverage: 4.8,
    reviewCount: 88,
    specifications: [{ label: 'Weight', value: '3 lbs (1.36 kg)' }],
    updatedAt: new Date().toISOString(),
  },

  // --- HEALTH & SUPPLEMENTS ---
  {
    id: 'prod-006',
    slug: 'nature-made-vitamin-d3-2000-iu',
    gtin: '031604026548',
    name: 'Nature Made Vitamin D3 1000 IU (25 mcg)',
    brand: 'Nature Made',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: 'Pharmacist recommended USP verified softgels supporting bone, teeth, muscle, and immune health (300 Softgels).',
    price: 5000,
    currency: 'BIRR',
    images: [{ url: '/products/nature-made-vitamin-d3-2000-iu.avif', altText: 'Nature Made Vitamin D3 Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 100,
    ratingAverage: 4.9,
    reviewCount: 420,
    specifications: [{ label: 'Count', value: '300 Softgels' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-007',
    slug: 'youtheory-verisol-collagen-345-tablets',
    gtin: '085324400330',
    name: 'Youtheory VERISOL Collagen Advanced Formula',
    brand: 'Youtheory',
    categorySlug: 'supplements',
    subCategorySlug: 'collagen',
    description: 'Concentrated effect formula with Biotin & Antioxidants to minimize wrinkles and improve skin elasticity (345 Tablets).',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/youtheory-verisol-collagen-345-tablets.avif', altText: 'Youtheory VERISOL Collagen', isPrimary: true }],
    inStock: true,
    stockQuantity: 45,
    ratingAverage: 4.7,
    reviewCount: 175,
    specifications: [{ label: 'Count', value: '345 Tablets' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-008',
    slug: 'youtheory-ashwagandha-1000mg-180-capsules',
    gtin: '085324400385',
    name: 'Youtheory Ashwagandha 1000 mg',
    brand: 'Youtheory',
    categorySlug: 'supplements',
    subCategorySlug: 'herbal',
    description: 'Daily adaptogen formula supporting a healthy stress response (180 Vegetarian Capsules).',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/youtheory-ashwagandha-1000mg-180-capsules.avif', altText: 'Youtheory Ashwagandha Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 35,
    ratingAverage: 4.8,
    reviewCount: 92,
    specifications: [{ label: 'Count', value: '180 Vegetarian Capsules' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-009',
    slug: 'nature-made-fish-oil-2400mg-300-softgels',
    gtin: '031604015283',
    name: 'Nature Made Fish Oil 2400 mg (720 mg Omega-3)',
    brand: 'Nature Made',
    categorySlug: 'supplements',
    subCategorySlug: 'omega-3',
    description: 'Purified to remove mercury. Supports a healthy heart (300 Softgels / 150 Doses).',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/nature-made-fish-oil-2400mg-300-softgels.avif', altText: 'Nature Made Fish Oil Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 70,
    ratingAverage: 4.9,
    reviewCount: 280,
    specifications: [{ label: 'Count', value: '300 Softgels' }],
    updatedAt: new Date().toISOString(),
  },

  // --- PERSONAL CARE & HYGIENE ---
  {
    id: 'prod-010',
    slug: 'dove-original-beauty-bar-16-pack',
    gtin: '011111613769',
    name: 'Dove Original Beauty Bar Soap (1 piece)',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'bar-soap',
    description: 'Classic moisturizing bar cleanser formulated with 1/4 moisturizing cream to leave skin soft, smooth, and nourished.',
    price: 350,
    currency: 'BIRR',
    images: [
      {
        url: '/products/dove-16-bars.avif',
        altText: 'Dove Original Beauty Bar Soap 16 Pack Box',
        isPrimary: true,
      },
    ],
    inStock: true,
    stockQuantity: 40,
    ratingAverage: 4.9,
    reviewCount: 530,
    specifications: [
      { label: 'Count', value: '16 Bars' },
      { label: 'Net Weight', value: '60 oz Total (16 x 3.75 oz / 106g)' },
      { label: 'Formula', value: '1/4 Moisturizing Cream, Sulfate-Free' },
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-011',
    slug: 'cetaphil-moisturizing-lotion-2pack',
    gtin: '302993910202',
    name: 'Cetaphil Moisturizing Lotion',
    brand: 'Cetaphil',
    categorySlug: 'personal-care',
    subCategorySlug: 'lotions',
    description: 'Lightweight lotion with Glycerin, Vitamins B3 & B5 for normal to dry skin hydration (Two 20 fl oz bottles).',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/cetaphil-moisturizing-lotion-2pack.avif', altText: 'Cetaphil Moisturizing Lotion 2-Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 50,
    ratingAverage: 4.9,
    reviewCount: 410,
    specifications: [{ label: 'Volume', value: '40 fl oz Total (2 x 20 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-012',
    slug: 'cerave-facial-moisturizing-lotion-3pack',
    gtin: '360600053738',
    name: 'CeraVe AM/PM Facial Moisturizing',
    brand: 'CeraVe',
    categorySlug: 'personal-care',
    subCategorySlug: 'lotions',
    description: '3 essential ceramides formula including AM Broad Spectrum SPF 30 lotion (3 Pack bundle).',
    price: 3800,
    currency: 'BIRR',
    images: [{ url: '/products/cerave-facial-moisturizing-lotion-3pack.avif', altText: 'CeraVe Facial Moisturizing Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 30,
    ratingAverage: 4.8,
    reviewCount: 320,
    specifications: [{ label: 'Set Includes', value: 'Facial Lotion AM SPF 30 & PM Lotions' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-013',
    slug: 'old-spice-swagger-deodorant-4pack',
    gtin: '037000976521',
    name: 'Old Spice Swagger Aluminum-Free Deodorant',
    brand: 'Old Spice',
    categorySlug: 'personal-care',
    subCategorySlug: 'deodorant',
    description: 'Long-lasting 24/7 freshness with Cedarwood scent (Four 3.0 oz deodorant sticks).',
    price: 2500,
    currency: 'BIRR',
    images: [{ url: '/products/old-spice-4pack.avif', 
               altText: 'Old Spice Swagger Deodorant 4-Pack', 
               isPrimary: true }
            ],
    inStock: true,
    stockQuantity: 45,
    ratingAverage: 4.7,
    reviewCount: 195,
    specifications: [{ label: 'Weight', value: '12 oz Total (4 x 3.0 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-014',
    slug: 'olay-essential-botanicals-body-wash',
    gtin: '037000847164',
    name: 'Olay Essential Botanicals Body Wash',
    brand: 'Olay',
    categorySlug: 'personal-care',
    subCategorySlug: 'body-wash',
    description: 'Nourishing body wash trio infused with essential botanicals and Vitamin B3 complex. Includes Lavender Milk & Sandalwood, Spiced Chai & Pear, and White Tea & Cucumber.',
    price: 5000,
    currency: 'BIRR',
    images: [
      {
        url: '/products/olay-3-body- washes.jpg',
        altText: 'Olay Essential Botanicals Body Wash 3-Pack',
        isPrimary: true,
      },
    ],
    inStock: true,
    stockQuantity: 35,
    ratingAverage: 4.9,
    reviewCount: 168,
    specifications: [
      { label: 'Volume', value: '70.8 fl oz Total (3 x 23.6 fl oz / 700 mL)' },
      {
        label: 'Scents Included',
        value: 'Lavender Milk & Sandalwood, Spiced Chai & Pear, White Tea & Cucumber',
      },
      { label: 'Key Ingredient', value: 'Vitamin B3 Complex' },
    ],
    updatedAt: new Date().toISOString(),
  },

  // --- MATERIALS FROM THE STORE MATERIALS EXCEL SHEET (NON-DUPLICATE ITEMS) ---
  {
    id: 'prod-015',
    slug: 'colgate-total',
    gtin: '',
    name: 'Colgate Total',
    brand: 'Colgate',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Colgate Total',
    price: 2300,
    currency: 'BIRR',
    images: [{ url: '/products/colgate-total.avif', altText: 'Colgate Total', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2300' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-016',
    slug: 'gillette-ultimate-protection',
    gtin: '',
    name: 'Gillette Ultimate Protection',
    brand: 'Gillette',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Gillette Ultimate Protection',
    price: 2900,
    currency: 'BIRR',
    images: [{ url: '/products/Gillette-Ultimate-Protection.jpg', altText: 'Gillette Ultimate Protection', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2900' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-017',
    slug: 'cheerios',
    gtin: '',
    name: 'Cheerios',
    brand: 'Cheerios',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Cheerios',
    price: 2000,
    currency: 'BIRR',
    images: [{ url: '/products/Cheerios-Oats.jpg', altText: 'Cheerios', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000 old price' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-018',
    slug: 'krkland-organic-maple-syrup',
    gtin: '',
    name: 'Krkland Organic Maple Syrup',
    brand: 'Krkland',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Krkland Organic Maple Syrup. Source price: . Price was not provided in the source sheet.',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Krkland-Organic-Maple-Syrup.jpg', altText: 'Krkland Organic Maple Syrup', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-019',
    slug: 'kirkland-organic-honey',
    gtin: '',
    name: 'Kirkland Organic Honey',
    brand: 'Kirkland',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Kirkland Organic Honey',
    price: 2500,
    currency: 'BIRR',
    images: [{ url: '/products/Kirkland-Organic-Honey.jpg', altText: 'Kirkland Organic Honey', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-020',
    slug: 'dove-advanced-care-invisible',
    gtin: '',
    name: 'Dove Advanced Care Invisible',
    brand: 'Dove',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Dove Advanced Care Invisible. Source price: 2400. For a price range, the maximum price was used.',
    price: 2400,
    currency: 'BIRR',
    images: [{ url: '/products/Dove-Advanced-Care-Invisible.avif', altText: 'Dove Advanced Care Invisible', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2400' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-021',
    slug: 'dove-intensive-repair',
    gtin: '',
    name: 'Dove Intensive Repair',
    brand: 'Dove',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Dove Intensive Repair',
    price: 5000,
    currency: 'BIRR',
    images: [{ url: '/products/Dove-Intensive-Repair.avif', altText: 'Dove Intensive Repair', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '4500-5000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-022',
    slug: 'jif-creamy-peanut-butter',
    gtin: '',
    name: 'Jif Creamy Peanut Butter',
    brand: 'Jif',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Jif Creamy Peanut Butter',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/Jif-Creamy-Peanut-Butter.jpg', altText: 'Jif Creamy Peanut Butter', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2500-4000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-023',
    slug: 'cinnamon-toast-crunch',
    gtin: '',
    name: 'Cinnamon Toast Crunch',
    brand: 'Cinnamon',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Cinnamon Toast Crunch',
    price: 4900,
    currency: 'BIRR',
    images: [{ url: '/products/Cinnamon-Toast-Crunch.jpg', altText: 'Cinnamon Toast Crunch', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '4000-4900' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-024',
    slug: 'tresemme-hydration-smoothness-and-shine',
    gtin: '',
    name: 'Tresemme Hydration Smoothness and Shine',
    brand: 'Tresemme',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Tresemme Hydration Smoothness and Shine',
    price: 8000,
    currency: 'BIRR',
    images: [{ url: '/products/Tresemme-Hydration-Smoothness-and-Shine.jpg', altText: 'Tresemme Hydration Smoothness and Shine', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '8000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-025',
    slug: 'aveeno-daily-moisturizing-lotion',
    gtin: '',
    name: 'Aveeno Daily Moisturizing Lotion',
    brand: 'Aveeno',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Aveeno Daily Moisturizing Lotion',
    price: 5500,
    currency: 'BIRR',
    images: [{ url: '/products/Aveeno-Daily-Moisturizing-Lotion.jpg', altText: 'Aveeno Daily Moisturizing Lotion', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '5000-5500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-026',
    slug: 'sensodyne-sensitivity-protection',
    gtin: '',
    name: 'Sensodyne Sensitivity Protection',
    brand: 'Sensodyne',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Sensodyne Sensitivity Protection',
    price: 3300,
    currency: 'BIRR',
    images: [{ url: '/products/Sensodyne-Sensitivity-Protection.jpg', altText: 'Sensodyne Sensitivity Protection', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2500-3300' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-027',
    slug: 'crest-pro-health-advanced',
    gtin: '',
    name: 'Crest Pro-Health Advanced',
    brand: 'Crest',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Crest Pro-Health Advanced',
    price: 2500,
    currency: 'BIRR',
    images: [{ url: '/products/Crest-Pro-Health-Advanced.avif', altText: 'Crest Pro-Health Advanced', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-028',
    slug: 'irish-spring',
    gtin: '',
    name: 'Irish Spring',
    brand: 'Irish',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Irish Spring',
    price: 700,
    currency: 'BIRR',
    images: [{ url: '/products/Irish-Spring.jpg', altText: 'Irish Spring', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '500-700' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-029',
    slug: 'kirkland-pistachios',
    gtin: '',
    name: 'Kirkland Pistachios',
    brand: 'Kirkland',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Kirkland Pistachios',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/Kirkland-Pistachios.jpg', altText: 'Kirkland Pistachios', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '6000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-030',
    slug: 'trident',
    gtin: '',
    name: 'Trident',
    brand: 'Trident',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Trident',
    price: 500,
    currency: 'BIRR',
    images: [{ url: '/products/Trident-gum.jpg', altText: 'Trident', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-031',
    slug: 'degree-ultra-clear',
    gtin: '',
    name: 'Degree Ultra Clear',
    brand: 'Degree',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Degree Ultra Clear',
    price: 2300,
    currency: 'BIRR',
    images: [{ url: '/products/Degree-Ultra-Clear.avif', altText: 'Degree Ultra Clear', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2300' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-032',
    slug: 'extra-long-lasting-flavor',
    gtin: '',
    name: 'Extra Long Lasting Flavor',
    brand: 'Extra',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Extra Long Lasting Flavor',
    price: 500,
    currency: 'BIRR',
    images: [{ url: '/products/Extra-Long-Lasting-Flavor.jpg', altText: 'Extra Long Lasting Flavor', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-033',
    slug: 'oreo',
    gtin: '',
    name: 'Oreo',
    brand: 'Oreo',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Oreo',
    price: 1000,
    currency: 'BIRR',
    images: [{ url: '/products/Oreo-biscuts.jpg', altText: 'Oreo', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '1000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-034',
    slug: 'dove-deep-moisture',
    gtin: '',
    name: 'Dove Deep Moisture',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Dove Deep Moisture',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/Dove-Deep-Moisture.avif', altText: 'Dove Deep Moisture', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '4000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-038',
    slug: 'one-a-day-womans-complete-multi-vitamin',
    gtin: '',
    name: 'One A Day Womans Complete Multi-vitamin',
    brand: 'One',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: 'One A Day Womans Complete Multi-vitamin',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/One-A-Day-Womans-Complete-Multi-vitamin.avif', altText: 'One A Day Womans Complete Multi-vitamin', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '6500-7500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-039',
    slug: 'nature-made-prenatal',
    gtin: '',
    name: 'Nature Made Prenatal',
    brand: 'Nature',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: 'Nature Made Prenatal',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/Nature-Made-Prenatal.avif', altText: 'Nature Made Prenatal', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '7500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-040',
    slug: 'heinz-tomato-ketchup',
    gtin: '',
    name: 'Heinz Tomato Ketchup',
    brand: 'Heinz',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Heinz Tomato Ketchup',
    price: 2800,
    currency: 'BIRR',
    images: [{ url: '/products/Heinz-Tomato-Ketchup.jpg', altText: 'Heinz Tomato Ketchup', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2500-2800' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-041',
    slug: 'sc-johnson-ziplock',
    gtin: '',
    name: 'Sc Johnson Ziplock',
    brand: 'Sc',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Sc Johnson Ziplock',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Sc-Johnson-Ziplock.jpg', altText: 'Sc Johnson Ziplock', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-042',
    slug: 'nutella-peanut',
    gtin: '',
    name: 'Nutella Peanut',
    brand: 'Nutella',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Nutella Peanut',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Nutella-Peanut.jpg', altText: 'Nutella Peanut', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-043',
    slug: 'shin-raymun',
    gtin: '',
    name: 'Shin Raymun',
    brand: 'Shin',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Shin Raymun',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Shin-Raymun.jpg', altText: 'Shin Raymun', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-044',
    slug: 'febreze-air-freshner',
    gtin: '',
    name: 'Febreze Air Freshner',
    brand: 'Febreze',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Febreze Air Freshner',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Febreze-Air-Freshner.jpg', altText: 'Febreze Air Freshner', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-045',
    slug: 'desitin-maximum-strength-paste',
    gtin: '',
    name: 'Desitin Maximum Strength Paste',
    brand: 'Desitin',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Desitin Maximum Strength Paste',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Desitin-Maximum-Strength-Paste.jpg', altText: 'Desitin Maximum Strength Paste', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-046',
    slug: 'colgate-individually-sealed-brushes',
    gtin: '',
    name: 'Colgate Individually Sealed Brushes',
    brand: 'Colgate',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Colgate Individually Sealed Brushes',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Colgate-Individually-Sealed-Brushes.jpg', altText: 'Colgate Individually Sealed Brushes', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-047',
    slug: 'blush-cardigen-fine-fregrance-mist',
    gtin: '',
    name: 'Blush Cardigen Fine Fregrance Mist',
    brand: 'Blush',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Blush Cardigen Fine Fregrance Mist',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Blush-Cardigen-Fine-Fregrance Mist.webp', altText: 'Blush Cardigen Fine Fregrance Mist', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'prod-048',
    slug: 'cheerios',
    gtin: '',
    name: 'Cheerios Toasted Whole Grain Oat cereal',
    brand: 'Cheerios',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'breakfast-cereal',
    description: 'Ready-to-eat toasted 100% whole-grain oat cereal',
    price: 2650,
    currency: 'BIRR',
    images: [{ url: '/products/cheerios.jpg', altText: 'Cheerios Toasted Whole Grain Oat cereal', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: '100 %Whole-grainain oat cereal; ready-to-eat;Gluten Free, Package size - (20.35 OZ) (576g)' }, { label: 'Brand', value: 'Cheerios' }, { label: 'Manufacturer', value: 'General Mills' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-049',
    slug: 'cinammentoast',
    gtin: '',
    name: 'Cinnamon Toast Crunch',
    brand: 'General Mills',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'breakfast-cereal',
    description: 'Crispy, Sweetened whole wheat and rice cereal flavored with cinnamon',
    price: 3500,
    currency: 'BIRR',
    images: [{ url: '/products/cinammentoast.jpg', altText: 'Cinnamon Toast Crunch', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Cinnamon-flavored; ready-to-eat; 2BAGS 3LB 1.5OZ(1.4KG)' }, { label: 'Brand', value: 'General Mills' }, { label: 'Manufacturer', value: 'General Mills' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-050',
    slug: 'chiaseeds',
    gtin: '',
    name: 'Chia Seeds',
    brand: 'MAYORGA organics',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'seeds-and-grains',
    description: 'Edible chia seeds commonly used in cereals, smoothies and cooking',
    price: 4100,
    currency: 'BIRR',
    images: [{ url: '/products/chiaseeds.jpg', altText: 'Chia Seeds', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Chia seeds; dry product; package size 3lb(1.36KG)' }, { label: 'Brand', value: 'MAYORGA organics' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-051',
    slug: 'ferrero-48pcs',
    gtin: '',
    name: 'Ferrero Collection 48 pcs',
    brand: 'Ferrero',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'chocolate-and-confectionery',
    description: 'Assortment of individually wrapped Ferrero chocolates',
    price: 6800,
    currency: 'BIRR',
    images: [{ url: '/products/ferrero-48pcs.jpg', altText: 'Ferrero Collection 48 pcs', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: '48 pieces; assorted chocolates; boxed' }, { label: 'Brand', value: 'Ferrero' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-052',
    slug: 'lindet-gold',
    gtin: '',
    name: 'Lindt Gold',
    brand: 'Lindt',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'chocolate-and-confectionery',
    description: 'Premium chocolate product in Lindt Gold packaging',
    price: 4400,
    currency: 'BIRR',
    images: [{ url: '/products/lindet-gold.jpg', altText: 'Lindt Gold', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Chocolate; package size/variety varies' }, { label: 'Brand', value: 'Lindt' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-053',
    slug: 'bouchard-dark-beligian-chocolate',
    gtin: '',
    name: 'Bouchard Dark Belgian Chocolate',
    brand: 'Bouchard',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'chocolate-and-confectionery',
    description: 'Belgian dark chocolate bar',
    price: 6500,
    currency: 'BIRR',
    images: [{ url: '/products/bouchard-dark-beligian-chocolate.jpg', altText: 'Bouchard Dark Belgian Chocolate', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Dark chocolate; Belgian chocolate; cocoa content varies by variant' }, { label: 'Brand', value: 'Bouchard' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-054',
    slug: 'nutty-fruity-dubai-chocolate-bars',
    gtin: '',
    name: 'Nutty Fruity Dubai Chocolate Bars',
    brand: 'Nutty Fruity',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'chocolate-and-confectionery',
    description: 'Chocolate bars inspired by Dubai-style chocolate, typically containing a nutty/crispy filling',
    price: 4550,
    currency: 'BIRR',
    images: [{ url: '/products/nutty-fruity-dubai-chocolate-bars.jpg', altText: 'Nutty Fruity Dubai Chocolate Bars', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Chocolate bar; filling/weight varies' }, { label: 'Brand', value: 'Nutty Fruity' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-055',
    slug: 'godiva-milk-chocolate',
    gtin: '',
    name: 'Godiva Milk Chocolate',
    brand: 'Godiva',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'chocolate-and-confectionery',
    description: 'Premium milk chocolate confectionery',
    price: 4450,
    currency: 'BIRR',
    images: [{ url: '/products/godiva-milk-chocolate.jpg', altText: 'Godiva Milk Chocolate', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Milk chocolate; package size varies' }, { label: 'Brand', value: 'Godiva' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-056',
    slug: 'one-a-day-women-multivitamins',
    gtin: '',
    name: 'One A Day Women\'s Multivitamin',
    brand: 'One A Day',
    categorySlug: 'health-and-wellness',
    subCategorySlug: 'multivitamins',
    description: 'Daily multivitamWOMENS complete multivitamin supplement key nutrients including VITAMINS A, C, D, &E VITAMINS B6 & B12 BIOTIN  , IRON',
    price: 6800,
    currency: 'BIRR',
    images: [{ url: '/products/one-a-day-women-multivitamins.jpg', altText: 'One A Day Women\'s Multivitamin', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Women\'s multivitamin; 3OO TABLETS' }, { label: 'Brand', value: 'One A Day' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-057',
    slug: 'vitamind3',
    gtin: '',
    name: 'Vitamin D3',
    brand: 'Nature Made',
    categorySlug: 'health-and-wellness',
    subCategorySlug: 'vitamins',
    description: 'supports immune health,supports bone,teeth & muscle health',
    price: 6800,
    currency: 'BIRR',
    images: [{ url: '/products/vitamind3.jpg', altText: 'Vitamin D3', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Vitamin D3; 1000IU(25mcg),650 SOFTGELS' }, { label: 'Brand', value: 'Nature Made' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-058',
    slug: 'ashewangeda',
    gtin: '',
    name: 'Ashwagandha',
    brand: 'Youtheory',
    categorySlug: 'health-and-wellness',
    subCategorySlug: 'herbal-supplements',
    description: 'daily adaptogen  formula dietary suppliment, supports a healthy stress response',
    price: 6800,
    currency: 'BIRR',
    images: [{ url: '/products/ashewangeda.jpg', altText: 'Ashwagandha', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'ashwagandha,1000mg per daily serving,180 vegetarian capsules' }, { label: 'Brand', value: 'Youtheory' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-059',
    slug: 'fishoil',
    gtin: '',
    name: 'Fish Oil',
    brand: 'Nature Made',
    categorySlug: 'health-and-wellness',
    subCategorySlug: 'omega-3-supplements',
    description: 'Fish-oil dietary supplement providing omega-3 fatty acids, purified to remove mercury, helps support a healthy heart',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/fishoil.jpg', altText: 'Fish Oil', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Fish oil; 2400 mg (720 mg Omega-3,  Omega-3 EPA and DHA 600mg) per 2 soft Gels, 300 Soft Gels' }, { label: 'Brand', value: 'Nature Made' }, { label: 'Manufacturer', value: 'Nature Made' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-060',
    slug: 'prenatal',
    gtin: '',
    name: 'Prenatal Multivitamin',
    brand: 'Nature Made',
    categorySlug: 'health-and-wellness',
    subCategorySlug: 'prenatal-vitamins',
    description: 'Multivitamin with 20 key nutrients, supplement formulated for pregnancy, Clinically Proven Absorption of Folic Acid & Iron, supports the development of baby\'s brain, eyes & nervous system',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/prenatal.jpg', altText: 'Prenatal Multivitamin', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Prenatal Multivitamin Folic Acid + DHA, orange Scent, 150 Soft Gels' }, { label: 'Brand', value: 'Nature Made' }, { label: 'Manufacturer', value: 'Nature Made' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-061',
    slug: 'magnesium-glycinate',
    gtin: '',
    name: 'Magnesium Glycinate',
    brand: 'Nature\'s Bounty',
    categorySlug: 'health-and-wellness',
    subCategorySlug: 'mineral-supplements',
    description: 'High Absorption Magnesium s Glycinate Supports Muscle Relaxation, Bone, heart and Nerve Health',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/magnesium-glycinate.jpg', altText: 'Magnesium Glycinate', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Magnesium glycinate; 240mg per serving, 180 Capsules' }, { label: 'Brand', value: 'Nature\'s Bounty' }, { label: 'Manufacturer', value: 'Nature\'s Bounty' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-062',
    slug: 'collagen',
    gtin: '',
    name: 'VERISOL Collagen',
    brand: 'Youtheory',
    categorySlug: 'health-and-wellness',
    subCategorySlug: 'health-and-wellness',
    description: 'Collagen dietary supplement clinically studied ingredient that helps minimize wrinkles + improve skin elasticity',
    price: 7100,
    currency: 'BIRR',
    images: [{ url: '/products/collagen.jpg', altText: 'VERISOL Collagen', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Collagen;  dietary Supplement , 345 Tablets' }, { label: 'Brand', value: 'Youtheory' }, { label: 'Manufacturer', value: 'nutrawise' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-063',
    slug: 'trident-fruit',
    gtin: '',
    name: 'Trident Fruit',
    brand: 'Trident',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'chewing-gum',
    description: ',trident refreshingly long lasting tropical twist,watermelon twist,island berry lime',
    price: 480,
    currency: 'BIRR',
    images: [{ url: '/products/trident-fruit.jpg', altText: 'Trident Fruit', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Chewing gum; fruit flavor; 20 packs 14 sticks per package' }, { label: 'Brand', value: 'Trident' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-064',
    slug: 'extra',
    gtin: '',
    name: 'Extra',
    brand: 'Extra',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'chewing-gum',
    description: 'Extra',
    price: 480,
    currency: 'BIRR',
    images: [{ url: '/products/extra.jpg', altText: 'Extra', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Chewing gum; mint flavour 18packs 15 sticks per pack' }, { label: 'Brand', value: 'Extra' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-065',
    slug: 'unsalted-nuts',
    gtin: '',
    name: 'Unsalted Nuts',
    brand: 'kirkland signature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'nuts-and-seeds',
    description: 'extra fancy unsalted mixed nuts with cashews ,almonds,pistachios, pecans',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/unsalted-nuts.jpg', altText: 'Unsalted Nuts', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Mixed/assorted nuts; unsalted; net wt 40oz(2.5lbs)1.13kg' }, { label: 'Brand', value: 'kirkland signature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-066',
    slug: 'salted-mixed-nuts',
    gtin: '',
    name: 'Salted Mixed Nuts',
    brand: 'kirkland signature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'nuts-and-seeds',
    description: 'Salted Mixed Nuts',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/salted-mixed-nuts.jpg', altText: 'Salted Mixed Nuts', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Mixed nuts; salted; 40oz(2.5lbs) 1.13kg' }, { label: 'Brand', value: 'kirkland signature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-067',
    slug: 'cashews',
    gtin: '',
    name: 'Cashews',
    brand: 'kirkland signature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'nuts-and-seeds',
    description: 'fancy whole cashews with seasalt',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/cashews.jpg', altText: 'Cashews', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'whole sahews net wt 40oz(2.5lbs)1.13kg' }, { label: 'Brand', value: 'kirkland signature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-068',
    slug: 'almonds',
    gtin: '',
    name: 'Almonds',
    brand: 'kirkland signature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'nuts-and-seeds',
    description: 'us#1 supreme whole steam pasteurized almonds',
    price: 4900,
    currency: 'BIRR',
    images: [{ url: '/products/almonds.jpg', altText: 'Almonds', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Almonds; net wt 1.36kg(48oz) 3lbs' }, { label: 'Brand', value: 'kirkland signature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-069',
    slug: 'salted-pistachios',
    gtin: '',
    name: 'Salted Pistachios',
    brand: 'kirkland signature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'nuts-and-seeds',
    description: 'us#1 naturally opened roasted and salted pistachios',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/salted-pistachios.jpg', altText: 'Salted Pistachios', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Pistachios; roasted and salted net wt 1.36kgs(48oz) 3lbs' }, { label: 'Brand', value: 'kirkland signature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-070',
    slug: 'unsalted-pistachios',
    gtin: '',
    name: 'Unsalted Pistachios',
    brand: 'kirkland signature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'nuts-and-seeds',
    description: 'roasted and unsaled pisatchios witjh shell',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/unsalted-pistachios.jpg', altText: 'Unsalted Pistachios', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Pistachios; unsalted; roasted/ net wt 1.36kgs,(480z) 3lbs' }, { label: 'Brand', value: 'kirkland signature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-071',
    slug: 'quinoa',
    gtin: '',
    name: 'Quinoa',
    brand: 'kirkland signature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'grains-and-seeds',
    description: 'Edible quinoa grain  glutenfree used as a food ingredient or side dish',
    price: 7000,
    currency: 'BIRR',
    images: [{ url: '/products/quinoa.jpg', altText: 'Quinoa', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Quinoa; dry grain; 2.04kgs (4.5lbs)' }, { label: 'Brand', value: 'kirkland signature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-072',
    slug: 'nutella',
    gtin: '',
    name: 'Nutella',
    brand: 'Nutella',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'spreads',
    description: 'Hazelnut-cocoa spread for bread, desserts and other foods',
    price: 3800,
    currency: 'BIRR',
    images: [{ url: '/products/nutella.jpg', altText: 'Nutella', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Hazelnut cocoa spread; net wt 33.5oz (950g)' }, { label: 'Brand', value: 'Nutella' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-073',
    slug: 'nutella-peanut',
    gtin: '',
    name: 'Nutella Peanut',
    brand: 'Nutella',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'spreads',
    description: 'Peanut-flavored chocolate/nut spread.',
    price: 3500,
    currency: 'BIRR',
    images: [{ url: '/products/nutella-peanut.jpg', altText: 'Nutella Peanut', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Peanut and cocoa; 26.5OZ (750g)' }, { label: 'Brand', value: 'Nutella' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-074',
    slug: 'almond-butter',
    gtin: '',
    name: 'Almond Butter',
    brand: 'kirklandsignature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'nut-butter',
    description: 'creamy almond butter',
    price: 3800,
    currency: 'BIRR',
    images: [{ url: '/products/almond-butter.jpg', altText: 'Almond Butter', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Almond butter; smooth nry wy (27OZ) 1LB 765 g' }, { label: 'Brand', value: 'kirklandsignature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-075',
    slug: 'maple-syrup',
    gtin: '',
    name: 'Maple Syrup',
    brand: 'kirkland signature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'syrups-and-sweeteners',
    description: 'organic maple syrup 100% pure us grade A amber color rich taste',
    price: 5000,
    currency: 'BIRR',
    images: [{ url: '/products/maple-syrup.jpg', altText: 'Maple Syrup', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Maple syrup; 1liter' }, { label: 'Brand', value: 'kirkland signature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-076',
    slug: 'barbecue-sauce',
    gtin: '',
    name: 'Barbecue Sauce',
    brand: 'SWEET BABY RAY\'S',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'sauces-and-condiments',
    description: 'Savory-sweet sauce commonly used with grilled or roasted foods.',
    price: 3800,
    currency: 'BIRR',
    images: [{ url: '/products/barbecue-sauce.jpg', altText: 'Barbecue Sauce', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Brand', value: 'SWEET BABY RAY\'S' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-077',
    slug: 'jif-peanut-better',
    gtin: '',
    name: 'Jif Peanut Butter',
    brand: 'Jif',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'nut-butter',
    description: 'Peanut butter spread made from roasted peanuts.',
    price: 3400,
    currency: 'BIRR',
    images: [{ url: '/products/jif-peanut-better.jpg', altText: 'Jif Peanut Butter', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Brand', value: 'Jif' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-078',
    slug: 'honey',
    gtin: '',
    name: 'Honey',
    brand: 'kirkland signature',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'sweeteners',
    description: 'organic raw & unfiltered honey product of brazil',
    price: 2500,
    currency: 'BIRR',
    images: [{ url: '/products/honey.jpg', altText: 'Honey', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Honey; net wt 600g' }, { label: 'Brand', value: 'kirkland signature' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-079',
    slug: 'ketchup',
    gtin: '',
    name: 'Ketchup',
    brand: 'HEINZ',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'sauces-and-condiments',
    description: 'TOMATO KETCUP GROWN NOT MADE NO ARTIFICAL FLAVORS,PRESERVATIVES OR COLORS',
    price: 2800,
    currency: 'BIRR',
    images: [{ url: '/products/ketchup.jpg', altText: 'Ketchup', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'TOMATO KETCHUP (1.25KG)' }, { label: 'Brand', value: 'HEINZ' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-080',
    slug: 'graza-extra-virgin-olive-oil',
    gtin: '',
    name: 'Extra Virgin Olive Oil',
    brand: 'Graza',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'cooking-oils',
    description: 'Extra virgin olive oil NO BLENDING, NO FUNNY BUSINESS, JUST 100% PURE PICUAL OLIVE OIL FROM JAEN,SPAIN',
    price: 3500,
    currency: 'BIRR',
    images: [{ url: '/products/graza-extra-virgin-olive-oil.jpg', altText: 'Extra Virgin Olive Oil', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Cooking Oil , 100% pure Picual olive oil, 750ml, about 50 serving per container (Serving Size 1Tbsp)' }, { label: 'Brand', value: 'Graza' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-081',
    slug: 'dove-soap-original',
    gtin: '',
    name: 'Dove Soap',
    brand: 'Dove',
    categorySlug: 'uncategorized',
    subCategorySlug: 'bath-and-body',
    description: 'BEAUTY BAR WITH DEEP MOISTURE',
    price: 520,
    currency: 'BIRR',
    images: [{ url: '/products/dove-soap-original.jpg', altText: 'Dove Soap', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Beauty bar; (106G)' }, { label: 'Brand', value: 'Dove' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-082',
    slug: 'irish-spring',
    gtin: '',
    name: 'Irish Spring',
    brand: 'Irish Spring',
    categorySlug: 'personal-care',
    subCategorySlug: 'bath-and-body',
    description: '12HR FRESH DEODRANT SOAP FEEL CLEAN AND FRESH',
    price: 470,
    currency: 'BIRR',
    images: [{ url: '/products/irish-spring.jpg', altText: 'Irish Spring', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Soap/body cleansing product; format and size vary' }, { label: 'Brand', value: 'Irish Spring' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-083',
    slug: 'olay-bodywash',
    gtin: '',
    name: 'Olay Body Wash',
    brand: 'Olay',
    categorySlug: 'personal-care',
    subCategorySlug: 'bath-and-body',
    description: 'BODY WASH INFUSED WITH ESSENTIAL OILS AND VITAMIN B3 COMLEX FOR FRESH AND RADIANT SKIN LONG LASTING FRAGRANCE  AVALABLE WITH VARIETY OF SCENTS',
    price: 3600,
    currency: 'BIRR',
    images: [{ url: '/products/olay-bodywash.jpg', altText: 'Olay Body Wash', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Liquid body wash; fragrance (700ML)' }, { label: 'Brand', value: 'Olay' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-084',
    slug: 'dove-lotion',
    gtin: '',
    name: 'Dove LOTION',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'bath-and-body',
    description: 'BODY LOTION  UNVEIL SOFTER,RADIANT SKIN WITH CREAMY LATHER AND THE ORIGIANAL',
    price: 3400,
    currency: 'BIRR',
    images: [{ url: '/products/dove-lotion.jpg', altText: 'Dove LOTION', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: '24HRS BODY LOTION 23FL OZ' }, { label: 'Brand', value: 'Dove' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-085',
    slug: 'dove-advanced-deodorant',
    gtin: '',
    name: 'Dove Advanced Deodorant',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'deodorants',
    description: 'Deodorant ADVANCED CARE 72HR-INVISIBLE ANTIPERSPIRANT DEODRANT CUCUMBER AND CACTUS WATER',
    price: 2200,
    currency: 'BIRR',
    images: [{ url: '/products/dove-advanced-deodorant.jpg', altText: 'Dove Advanced Deodorant', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Deodorant; ROLL ON (74G)' }, { label: 'Brand', value: 'Dove' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-086',
    slug: 'oldspice-deodorant',
    gtin: '',
    name: 'Old Spice Deodorant',
    brand: 'Old Spice',
    categorySlug: 'personal-care',
    subCategorySlug: 'deodorants',
    description: 'Men\'s deodoraDRANT ALMUNINUM FREE PROTECTION SWAGGWETRANSFORMSTJE UNFRESH INTO LEGEDS OF CONFIDENCE SCENT BOOSTED WITH ANTIOXIDENTS',
    price: 2100,
    currency: 'BIRR',
    images: [{ url: '/products/oldspice-deodorant.jpg', altText: 'Old Spice Deodorant', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Deodorant; STICK (85G)' }, { label: 'Brand', value: 'Old Spice' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-087',
    slug: 'gillet-deodorant',
    gtin: '',
    name: 'Gillette Deodorant',
    brand: 'Gillette',
    categorySlug: 'personal-care',
    subCategorySlug: 'deodorants',
    description: 'ULTIMATE PROTECTION NON IRRITANT  72HR ANTIPERSPIRANT PROTECTION',
    price: 2100,
    currency: 'BIRR',
    images: [{ url: '/products/gillet-deodorant.jpg', altText: 'Gillette Deodorant', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Deodorant/antiperspirant; STICK (107G)+-8**536' }, { label: 'Brand', value: 'Gillette' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-088',
    slug: 'degree-deodorant',
    gtin: '',
    name: 'Degree Deodorant',
    brand: 'Degree',
    categorySlug: 'personal-care',
    subCategorySlug: 'deodorants',
    description: 'Deodorant/antiperspirant FOR MEN designed for odor and sweat protection.',
    price: 2000,
    currency: 'BIRR',
    images: [{ url: '/products/degree-deodorant.jpg', altText: 'Degree Deodorant', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'DEODRANT/ANTIPERSPIRANT STICK (74G)' }, { label: 'Brand', value: 'Degree' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-089',
    slug: 'dove-shampoo',
    gtin: '',
    name: 'Dove Shampoo',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'hair-care',
    description: 'INTENSIVE REPAIR SHAMPOO DAMAGE THERAPY  BIO PROTEIN CARE +AMINO SERUM STOP 98% OF VISIBLE DAMAGE ,BREAKAGE , SYSTEM VS NON CONDITIONING SHAMPOO',
    price: 4200,
    currency: 'BIRR',
    images: [{ url: '/products/dove-shampoo.jpg', altText: 'Dove Shampoo', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Shampoo; formula 33.8 FL OZ (1L)' }, { label: 'Brand', value: 'Dove' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-090',
    slug: 'dove-conditioner',
    gtin: '',
    name: 'Dove Conditioner',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'hair-care',
    description: 'DOVE INTENSIVE REPAIR DAMAGE THERAPY BIO PROTEIN CARE + AMINO  SERUM IT PROTECTS, REPAIRS AND RESTORES HAIR TO REDUCE SIGNS OF DAMAGE',
    price: 4200,
    currency: 'BIRR',
    images: [{ url: '/products/dove-conditioner.jpg', altText: 'Dove Conditioner', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Conditioner; 33.8 FL OZ (1 L)' }, { label: 'Brand', value: 'Dove' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-091',
    slug: 'nexxus-shampoo',
    gtin: '',
    name: 'Nexxus Shampoo',
    brand: 'Nexxus',
    categorySlug: 'personal-care',
    subCategorySlug: 'hair-care',
    description: 'Hair shampoo formulated for advanced hydration for dry & brittle',
    price: 4500,
    currency: 'BIRR',
    images: [{ url: '/products/nexxus-shampoo.jpg', altText: 'Nexxus Shampoo', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Shampoo; 32FL OZ (1 QL)' }, { label: 'Brand', value: 'Nexxus' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-092',
    slug: 'nexxus-conditioner',
    gtin: '',
    name: 'Nexxus Conditioner',
    brand: 'Nexxus',
    categorySlug: 'personal-care',
    subCategorySlug: 'hair-care',
    description: 'Nexxus Conditioner',
    price: 4500,
    currency: 'BIRR',
    images: [{ url: '/products/nexxus-conditioner.jpg', altText: 'Nexxus Conditioner', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Conditioner; 32FL OZ (1QL)' }, { label: 'Brand', value: 'Nexxus' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-093',
    slug: 'tresemme-shampoo',
    gtin: '',
    name: 'TRESemmé Shampoo',
    brand: 'TRESemmé',
    categorySlug: 'personal-care',
    subCategorySlug: 'hair-care',
    description: 'Hair-care prODUCT ULTIMATE MOISTURE  72HRS HYDRATION SMOOTHNESS & SHINE HEAT PROTECTION',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/tresemme-shampoo.jpg', altText: 'TRESemmé Shampoo', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'TRESemme professional quality hyaluronic & Glycerin (1.15L)' }, { label: 'Brand', value: 'TRESemmé' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-094',
    slug: 'tresemme-conditioner',
    gtin: '',
    name: 'TRESemmé Conditioner',
    brand: 'TRESemmé',
    categorySlug: 'personal-care',
    subCategorySlug: 'hair-care',
    description: 'ultimate moisture conditioner creates your desire look with long lasting smoothness and brilliant shine from our ultimate moisture system 72 hrs hydration smoothness & shine',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/tresemme-conditioner.jpg', altText: 'TRESemmé Conditioner', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'TRESemme professional quality hyaluronic & Glycerin (1.15L)' }, { label: 'Brand', value: 'TRESemmé' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-095',
    slug: 'head-and-shoulder-shampoo',
    gtin: '',
    name: 'Head & Shoulders Shampoo',
    brand: 'Head & Shoulders',
    categorySlug: 'personal-care',
    subCategorySlug: 'hair-care',
    description: '2 IN 1 ANTI-dandruff shampoo for scalp and hair  CLEASNING WITH ALOEVERA,COCOUNTWATER?& VITAMINS E,B3',
    price: 6900,
    currency: 'BIRR',
    images: [{ url: '/products/head-and-shoulder-shampoo.jpg', altText: 'Head & Shoulders Shampoo', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Brand', value: 'Head & Shoulders' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-096',
    slug: 'sensodyne-toothpaste',
    gtin: '',
    name: 'Sensodyne Toothpaste',
    brand: 'Sensodyne',
    categorySlug: 'personal-care',
    subCategorySlug: 'oral-care',
    description: 'Toothpaste formulated for sensitive teeth.and cavity prevention 24?7 sensitivity protection+ strong & healthy teeth',
    price: 2700,
    currency: 'BIRR',
    images: [{ url: '/products/sensodyne-toothpaste.jpg', altText: 'Sensodyne Toothpaste', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Sensitive-teeth toothpaste; advanced whitening (184g)' }, { label: 'Brand', value: 'Sensodyne' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-097',
    slug: 'crest-pro-health-advanced',
    gtin: '',
    name: 'Crest Pro-Health Advanced',
    brand: 'Crest',
    categorySlug: 'personal-care',
    subCategorySlug: 'oral-care',
    description: 'Multi-benefit toothpaste for oral hygiene and protection.24 hour anti -bac protection whitening + intensive clean',
    price: 2000,
    currency: 'BIRR',
    images: [{ url: '/products/crest-pro-health-advanced.jpg', altText: 'Crest Pro-Health Advanced', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Toothpaste; fluoride (164)' }, { label: 'Brand', value: 'Crest' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-098',
    slug: 'crest-3d-white',
    gtin: '',
    name: 'Crest 3D White',
    brand: 'Crest',
    categorySlug: 'personal-care',
    subCategorySlug: 'oral-care',
    description: 'Whitening toothpaste designed to help remove surface stains.',
    price: 2000,
    currency: 'BIRR',
    images: [{ url: '/products/crest-3d-white.jpg', altText: 'Crest 3D White', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Whitening toothpaste; brilliant mint (147g)' }, { label: 'Brand', value: 'Crest' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-099',
    slug: 'colgate-tooth-paste',
    gtin: '',
    name: 'Colgate Toothpaste',
    brand: 'Colgate',
    categorySlug: 'personal-care',
    subCategorySlug: 'oral-care',
    description: 'Toothpaste for everyday dental hygiene total active protection anticavity, antigingivitis and antisensetivity',
    price: 1900,
    currency: 'BIRR',
    images: [{ url: '/products/colgate-tooth-paste.jpg', altText: 'Colgate Toothpaste', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Toothpaste; (118g)' }, { label: 'Brand', value: 'Colgate' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-100',
    slug: 'colgate-tooth-brush',
    gtin: '',
    name: 'Colgate Toothbrush',
    brand: 'Colgate',
    categorySlug: 'personal-care',
    subCategorySlug: 'oral-care',
    description: 'Manual toothbrush for daily oral cleaning. Fights root cause of oral care problems',
    price: 500,
    currency: 'BIRR',
    images: [{ url: '/products/colgate-tooth-brush.jpg', altText: 'Colgate Toothbrush', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Toothbrush' }, { label: 'Brand', value: 'Colgate' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-101',
    slug: 'cerave-daily-moisturizing',
    gtin: '',
    name: 'CeraVe Daily Moisturizing',
    brand: 'CeraVe',
    categorySlug: 'personal-care',
    subCategorySlug: 'skin-care',
    description: 'Daily moisturizing lotion dor normal and dryskin helps restore protective skin barrier',
    price: 5900,
    currency: 'BIRR',
    images: [{ url: '/products/cerave-daily-moisturizing.jpg', altText: 'CeraVe Daily Moisturizing', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Moisturizer; with 3 essential ceramides & hyaluronic acid (355ml)' }, { label: 'Brand', value: 'CeraVe' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-102',
    slug: 'cerave-spf30',
    gtin: '',
    name: 'CeraVe SPF30',
    brand: 'CeraVe',
    categorySlug: 'personal-care',
    subCategorySlug: 'sun-care',
    description: 'CeraVe oilfree f acial moisturizing lotion with sunscreen moisturizes through out the day & helps restore the protective skin barrier',
    price: 3900,
    currency: 'BIRR',
    images: [{ url: '/products/cerave-spf30.jpg', altText: 'CeraVe SPF30', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'SPF 30; with 3 essentials ceramides, niacinamide & hyaluronic acid( 89ml)' }, { label: 'Brand', value: 'CeraVe' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-103',
    slug: 'cetaphil-moisturizing-lotion',
    gtin: '',
    name: 'Cetaphil Moisturizing Lotion',
    brand: 'Cetaphil',
    categorySlug: 'personal-care',
    subCategorySlug: 'skin-care',
    description: 'light weight lotion hydrates for 48hhpurs leaving skin soft and smooth for normal & dry skin',
    price: 5400,
    currency: 'BIRR',
    images: [{ url: '/products/cetaphil-moisturizing-lotion.jpg', altText: 'Cetaphil Moisturizing Lotion', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'cetaphil with glycerin,vitaminsB3&B5 (591ml)' }, { label: 'Brand', value: 'Cetaphil' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-104',
    slug: 'aveeno-daily-moisturizing',
    gtin: '',
    name: 'Aveeno Daily Moisturizing',
    brand: 'Aveeno',
    categorySlug: 'personal-care',
    subCategorySlug: 'skin-care',
    description: 'Daily moisturizing lotion fragrance free normal-dry/sensitive skin instantly strengthens the skin barrier with 48 hrs hydration',
    price: 4300,
    currency: 'BIRR',
    images: [{ url: '/products/aveeno-daily-moisturizing.jpg', altText: 'Aveeno Daily Moisturizing', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Moisturizer/lotion; prebiotic oat (532ml)' }, { label: 'Brand', value: 'Aveeno' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-105',
    slug: 'eos-body-lotion',
    gtin: '',
    name: 'EOS Body Lotion',
    brand: 'eos',
    categorySlug: 'personal-care',
    subCategorySlug: 'skin-care',
    description: 'shea better 24h moisture body lotion 7 nourishing oils + butters soothing protection for dry skin',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/eos-body-lotion.jpg', altText: 'EOS Body Lotion', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Body lotion;vanilla cashmere (473ml)' }, { label: 'Brand', value: 'eos' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-106',
    slug: 'treehut-body-scrub',
    gtin: '',
    name: 'Tree Hut Body Scrub',
    brand: 'Tree Hut',
    categorySlug: 'personal-care',
    subCategorySlug: 'skin-care',
    description: 'Exfoliating body scrub for smoothing and cleansing the skin. Soothe + renew, variety type with different scent',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/treehut-body-scrub.jpg', altText: 'Tree Hut Body Scrub', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Body scrub;(595g)' }, { label: 'Brand', value: 'Tree Hut' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-107',
    slug: 'shine-n-jam-extra-hold-gel',
    gtin: '',
    name: 'Shine \'n Jam Extra Hold Gel',
    brand: 'Shine \'n Jam',
    categorySlug: 'personal-care',
    subCategorySlug: 'hair-styling',
    description: 'Extra-hold conditioning and styling gelwith honey extract',
    price: 2900,
    currency: 'BIRR',
    images: [{ url: '/products/shine-n-jam-extra-hold-gel.jpg', altText: 'Shine \'n Jam Extra Hold Gel', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Hair styling gel; extra hold (227g)' }, { label: 'Brand', value: 'Shine \'n Jam' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-108',
    slug: 'mille-rosemary-mint',
    gtin: '',
    name: 'Mielle Rosemary Mint Oil',
    brand: 'Mielle',
    categorySlug: 'personal-care',
    subCategorySlug: 'hair-care',
    description: 'Rosemary-based hair-care product  scalp & hair strengthening oil for daily use scalp treatment and split end care',
    price: 2400,
    currency: 'BIRR',
    images: [{ url: '/products/mille-rosemary-mint.jpg', altText: 'Mielle Rosemary Mint Oil', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'milelle 2 times biotin & jojoba oil (59ml)' }, { label: 'Brand', value: 'Mielle' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-109',
    slug: 'shin-ramyun',
    gtin: '',
    name: 'Shin Ramyun',
    brand: 'Nongshim',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'instant-noodles',
    description: 'Korean instant noodle product with spicy flavor.',
    price: 490,
    currency: 'BIRR',
    images: [{ url: '/products/shin-ramyun.jpg', altText: 'Shin Ramyun', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Instant noodles;  spicy (120g)' }, { label: 'Brand', value: 'Nongshim' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-110',
    slug: 'febrezze',
    gtin: '',
    name: 'Febreze',
    brand: 'Febreze',
    categorySlug: 'home-care',
    subCategorySlug: 'air-fresheners',
    description: 'Home fragrance and odor-eliminating air mistwith varity of scents',
    price: 1100,
    currency: 'BIRR',
    images: [{ url: '/products/febrezze.jpg', altText: 'Febreze', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Air freshener; spray (230g)' }, { label: 'Brand', value: 'Febreze' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-111',
    slug: 'ziploc',
    gtin: '',
    name: 'Ziploc',
    brand: 'Ziploc',
    categorySlug: 'household',
    subCategorySlug: 'food-storage',
    description: 'scjohnson resealable multi purpose storage bags and household food-storage',
    price: 2100,
    currency: 'BIRR',
    images: [{ url: '/products/ziploc.jpg', altText: 'Ziploc', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Storage bag/container 34 frezzer gallon (26.8cm8 27.3cm)' }, { label: 'Brand', value: 'Ziploc' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-112',
    slug: 'bath-and-body-works-fragrance-mist-women',
    gtin: '',
    name: 'Bath & Body Works Fragrance Mist Women',
    brand: 'Bath & Body Works',
    categorySlug: 'personal-care',
    subCategorySlug: 'fragrance',
    description: 'Women\'s body fragrance mist with variet of scent options',
    price: 3900,
    currency: 'BIRR',
    images: [{ url: '/products/bath-and-body-works-fragrance-mist-women.jpg', altText: 'Bath & Body Works Fragrance Mist Women', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Fragrance mist, (236ml)' }, { label: 'Brand', value: 'Bath & Body Works' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-113',
    slug: 'bath-and-body-work-body-lotion-women',
    gtin: '',
    name: 'Bath & Body Works Body Lotion Women',
    brand: 'Bath & Body Works',
    categorySlug: 'personal-care',
    subCategorySlug: 'skin-care',
    description: 'Women\'s body lotion for daily nourishing with shea butter + cocount oil 24 hour  moisture with variety of scent options',
    price: 3800,
    currency: 'BIRR',
    images: [{ url: '/products/bath-and-body-work-body-lotion-women.jpg', altText: 'Bath & Body Works Body Lotion Women', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Body lotion;(236ml)' }, { label: 'Brand', value: 'Bath & Body Works' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-114',
    slug: 'bathand-body-works-men-body-spray',
    gtin: '',
    name: 'Bath & Body Works Men\'s Body Spray',
    brand: 'Bath & Body Works',
    categorySlug: 'personal-care',
    subCategorySlug: 'fragrance',
    description: 'Men\'s body fragrance deodrazing spray 24hour odor protection variety scent options',
    price: 3850,
    currency: 'BIRR',
    images: [{ url: '/products/bathand-body-works-men-body-spray.jpg', altText: 'Bath & Body Works Men\'s Body Spray', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Body spray; (104g)' }, { label: 'Brand', value: 'Bath & Body Works' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-115',
    slug: 'bathand-body-works-shower-gel',
    gtin: '',
    name: 'Bath & Body Works Shower Gel',
    brand: 'Bath & Body Works',
    categorySlug: 'personal-care',
    subCategorySlug: 'bath-and-body',
    description: 'Shower gel/body wash  with pro vitamins B5 + aloe',
    price: 3850,
    currency: 'BIRR',
    images: [{ url: '/products/bathand-body-works-shower-gel.jpg', altText: 'Bath & Body Works Shower Gel', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Shower gel (295ml)' }, { label: 'Brand', value: 'Bath & Body Works' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-116',
    slug: 'goya-adobo-all-purpose-seasoning',
    gtin: '',
    name: 'Goya Adobo All Purpose Seasoning',
    brand: 'Goya',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'seasonings-and-spices',
    description: 'All-purpose seasoning blend used to flavor meat, poultry, seafood and other foods.',
    price: 3100,
    currency: 'BIRR',
    images: [{ url: '/products/goya-adobo-all-purpose-seasoning.jpg', altText: 'Goya Adobo All Purpose Seasoning', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Seasoning blend;(793g)' }, { label: 'Brand', value: 'Goya' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-117',
    slug: 'badia-all-purpose-seasoning',
    gtin: '',
    name: 'Badia All Purpose Seasoning',
    brand: 'Badia',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'seasonings-and-spices',
    description: 'All-purpose seasoning blend for cooking and food preparation.',
    price: 2950,
    currency: 'BIRR',
    images: [{ url: '/products/badia-all-purpose-seasoning.jpg', altText: 'Badia All Purpose Seasoning', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Seasoning blend,(793.8g)' }, { label: 'Brand', value: 'Badia' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-118',
    slug: 'big-bold-chicken-sweet-spicy-tangy-seasoning',
    gtin: '',
    name: 'Big Bold Chicken Sweet Spicy Tangy Seasoning',
    brand: 'Big Bold',
    categorySlug: 'food-and-beverage',
    subCategorySlug: 'seasonings-and-spices',
    description: 'Sweet, spicy and tangy seasoning intended for chicken and other foods.',
    price: 2700,
    currency: 'BIRR',
    images: [{ url: '/products/big-bold-chicken-sweet-spicy-tangy-seasoning.jpg', altText: 'Big Bold Chicken Sweet Spicy Tangy Seasoning', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'Chicken seasoning; sweet/spicy/tangy profile;(343g)' }, { label: 'Brand', value: 'Big Bold' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-119',
    slug: 'desitin',
    gtin: '',
    name: 'Desitin',
    brand: 'Desitin',
    categorySlug: 'personal-care',
    subCategorySlug: 'skin-protectant',
    description: 'smooth, daily barrier cream to prevent routine diaper rash maximum level skin protectant treatment and prevention of diaper rash, sealing out wetness and soothing chafed skin',
    price: 3000,
    currency: 'BIRR',
    images: [{ url: '/products/desitin.jpg', altText: 'Desitin', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'skin protectant (136g)' }, { label: 'Brand', value: 'Desitin' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-120',
    slug: 'vita-c-foam-cleanser',
    gtin: '',
    name: 'Vita C Foam Cleanser',
    brand: 'dearboo',
    categorySlug: 'personal-care',
    subCategorySlug: 'facial-cleanser',
    description: 'dark spot care  to brightens the skin, evens out blotchy tone,hydrate leaving your skin feeling refreshed and renewed every day',
    price: 3200,
    currency: 'BIRR',
    images: [{ url: '/products/vita-c-foam-cleanser.jpg', altText: 'Vita C Foam Cleanser', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'cleanse vitamin c complex, niacinamide & hyaluronic acid (230ml)' }, { label: 'Brand', value: 'dearboo' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-121',
    slug: 'cleansing-foam-hyaluronic-acid',
    gtin: '',
    name: 'Cleansing Foam Hyaluronic Acid',
    brand: 'softymo',
    categorySlug: 'personal-care',
    subCategorySlug: 'facial-cleanser',
    description: 'japanese 2 in 1 facial cleanser and makeup remover cleans deep seated pore impurities without stripping natural moisture skin feelingsoft,bouncy,and refreshed',
    price: 2400,
    currency: 'BIRR',
    images: [{ url: '/products/cleansing-foam-hyaluronic-acid.jpg', altText: 'Cleansing Foam Hyaluronic Acid', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'cleanser (190G)' }, { label: 'Brand', value: 'softymo' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-122',
    slug: 'snail-toner',
    gtin: '',
    name: 'Snail Toner',
    brand: 'dearboo',
    categorySlug: 'personal-care',
    subCategorySlug: 'facial-toner',
    description: 'light weight , hydrating korean skincare toner designed to prep the skin, improve dullness, promote radiant, glassy complexion',
    price: 2800,
    currency: 'BIRR',
    images: [{ url: '/products/snail-toner.jpg', altText: 'Snail Toner', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'toner (250ml)' }, { label: 'Brand', value: 'dearboo' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-123',
    slug: 'vita-c-toner',
    gtin: '',
    name: 'Vita C Toner',
    brand: 'dearboo',
    categorySlug: 'personal-care',
    subCategorySlug: 'facial-toner',
    description: 'korean facial skin care toner for dark spot correction ,firming  brightening and hydration',
    price: 3000,
    currency: 'BIRR',
    images: [{ url: '/products/vita-c-toner.jpg', altText: 'Vita C Toner', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'toner ( vitamin c complex,niacinamide,hyaluronic acid 250ml)' }, { label: 'Brand', value: 'dearboo' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-124',
    slug: 'snail-serum',
    gtin: '',
    name: 'Glass Skin Snail Serum',
    brand: 'dearboo',
    categorySlug: 'personal-care',
    subCategorySlug: 'face-serum',
    description: 'a korean product which is light weight ,hydrating facial treatment designed to soothe, plump and give the skin a radiant, dewy finish also helps absorb deep nutrients, smooths texture and supports skin regeneration',
    price: 2900,
    currency: 'BIRR',
    images: [{ url: '/products/snail-serum.jpg', altText: 'Glass Skin Snail Serum', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }, { label: 'Specification', value: 'serum snail mucin, hyaluronic acid, ceramide (100ml)' }, { label: 'Brand', value: 'dearboo' }],
    updatedAt: new Date().toISOString(),
  }
];

export async function getProductBySlug(slug: string): Promise<Product | null> {
  return MOCK_PRODUCTS.find((p) => p.slug === slug) || null;
}
