import { Product } from '@/types/ecommerce';

export const MOCK_PRODUCTS: Product[] = [
  // --- PANTRY & CONFECTIONERY ---
  {
    id: 'prod-001',
    slug: 'kirkland-unsalted-mixed-nuts-2-5lb',
    gtin: '096619284218',
    name: 'Kirkland Extra Fancy Unsalted Mixed Nuts',
    brand: 'Kirkland Signature',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'extra fancy unsalted mixed nuts with cashews, almonds, pistachios, pecans',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/kirkland-unsalted-mixed-nuts-2-5lb.avif', altText: 'Kirkland Unsalted Mixed Nuts', isPrimary: true }],
    inStock: true,
    stockQuantity: 50,
    ratingAverage: 4.9,
    reviewCount: 140,
    specifications: [{ label: 'Weight', value: '2.5 lbs (1.13 kg)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    slug: 'kirkland-salted-mixed-nuts-2-5lb',
    gtin: '096619164557',
    name: 'Kirkland Extra Fancy Salted Mixed Nuts',
    brand: 'Kirkland Signature',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Mixed nuts; salted; 40oz(2.5lbs) 1.13kg',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/kirkland-salted-mixed-nuts-2-5lb-blue.jpg', altText: 'Kirkland Salted Mixed Nuts', isPrimary: true }],
    inStock: true,
    stockQuantity: 40,
    ratingAverage: 4.8,
    reviewCount: 95,
    specifications: [{ label: 'Weight', value: '2.5 lbs (1.13 kg)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    slug: 'lindt-lindor-assorted-truffles-21-2oz',
    gtin: '003746601633',
    name: 'Lindt LINDOR Assorted Chocolate Truffles',
    brand: 'Lindt',
    categorySlug: 'pantry',
    subCategorySlug: 'confectionery',
    description: 'Premium chocolate product in Lindt Gold packaging',
    price: 4400,
    currency: 'BIRR',
    images: [{ url: '/products/lindt-lindor-assorted-truffles-21-2oz.avif', altText: 'Lindt Lindor Assorted Truffles', isPrimary: true }],
    inStock: true,
    stockQuantity: 30,
    ratingAverage: 4.9,
    reviewCount: 210,
    specifications: [{ label: 'Weight', value: '21.2 oz (600 g)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    slug: 'nutella-hazelnut-spread-2-pack',
    gtin: '009800895200',
    name: 'Nutella Hazelnut Spread with Cocoa (2 Pack)',
    brand: 'Nutella',
    categorySlug: 'pantry',
    subCategorySlug: 'spreads',
    description: 'Hazelnut-cocoa spread for bread, desserts and other foods',
    price: 3800,
    currency: 'BIRR',
    images: [{ url: '/products/nutella-hazelnut-spread-2-pack.avif', altText: 'Nutella Hazelnut Spread Twin Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 25,
    ratingAverage: 5.0,
    reviewCount: 310,
    specifications: [{ label: 'Net Weight', value: '67 oz Total (2 x 33.5 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    slug: 'mayorga-organic-chia-seeds-3lb',
    gtin: '089708000215',
    name: 'Mayorga Organics BIRRA Chia Seeds',
    brand: 'Mayorga Organics',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Edible chia seeds commonly used in cereals, smoothies and cooking',
    price: 4100,
    currency: 'BIRR',
    images: [{ url: '/products/mayorga-organic-chia-seeds-3lb.jpg', altText: 'Mayorga Organics Chia Seeds', isPrimary: true }],
    inStock: true,
    stockQuantity: 60,
    ratingAverage: 4.8,
    reviewCount: 88,
    specifications: [{ label: 'Weight', value: '3 lbs (1.36 kg)' }],
    updatedAt: new Date().toISOString(),
  },

  // --- HEALTH & SUPPLEMENTS ---
  {
    id: 'prod-006',
    slug: 'nature-made-vitamin-d3-2000-iu',
    gtin: '031604026548',
    name: 'Nature Made Vitamin D3 1000 IU (25 mcg)',
    brand: 'Nature Made',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: 'supports immune health, supports bone, teeth & muscle health',
    price: 6800,
    currency: 'BIRR',
    images: [{ url: '/products/nature-made-vitamin-d3-2000-iu.avif', altText: 'Nature Made Vitamin D3 Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 100,
    ratingAverage: 4.9,
    reviewCount: 420,
    specifications: [{ label: 'Count', value: '300 Softgels' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-007',
    slug: 'youtheory-verisol-collagen-345-tablets',
    gtin: '085324400330',
    name: 'Youtheory VERISOL Collagen Advanced Formula',
    brand: 'Youtheory',
    categorySlug: 'supplements',
    subCategorySlug: 'collagen',
    description: 'Collagen dietary supplement clinically studied ingredient that helps minimize wrinkles + improve skin elasticity',
    price: 7100,
    currency: 'BIRR',
    images: [{ url: '/products/youtheory-verisol-collagen-345-tablets.avif', altText: 'Youtheory VERISOL Collagen', isPrimary: true }],
    inStock: true,
    stockQuantity: 45,
    ratingAverage: 4.7,
    reviewCount: 175,
    specifications: [{ label: 'Count', value: '345 Tablets' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-008',
    slug: 'youtheory-ashwagandha-1000mg-180-capsules',
    gtin: '085324400385',
    name: 'Youtheory Ashwagandha 1000 mg',
    brand: 'Youtheory',
    categorySlug: 'supplements',
    subCategorySlug: 'herbal',
    description: 'daily adaptogen formula dietary supplement, supports a healthy stress response',
    price: 6800,
    currency: 'BIRR',
    images: [{ url: '/products/youtheory-ashwagandha-1000mg-180-capsules.avif', altText: 'Youtheory Ashwagandha Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 35,
    ratingAverage: 4.8,
    reviewCount: 92,
    specifications: [{ label: 'Count', value: '180 Vegetarian Capsules' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-009',
    slug: 'nature-made-fish-oil-2400mg-300-softgels',
    gtin: '031604015283',
    name: 'Nature Made Fish Oil 2400 mg (720 mg Omega-3)',
    brand: 'Nature Made',
    categorySlug: 'supplements',
    subCategorySlug: 'omega-3',
    description: 'Fish-oil dietary supplement providing omega-3 fatty acids, purified to remove mercury, helps support a healthy heart',
    price: 8000,
    currency: 'BIRR',
    images: [{ url: '/products/nature-made-fish-oil-2400mg-300-softgels.avif', altText: 'Nature Made Fish Oil Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 70,
    ratingAverage: 4.9,
    reviewCount: 280,
    specifications: [{ label: 'Count', value: '300 Softgels' }],
    updatedAt: new Date().toISOString(),
  },

  // --- PERSONAL CARE & HYGIENE ---
  {
    id: 'prod-010',
    slug: 'dove-original-beauty-bar-16-pack',
    gtin: '011111613769',
    name: 'Dove Original Beauty Bar Soap (1 piece)',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'bar-soap',
    description: 'Classic moisturizing bar cleanser formulated with 1/4 moisturizing cream to leave skin soft, smooth, and nourished.',
    price: 520,
    currency: 'BIRR',
    images: [
      {
        url: '/products/dove-16-bars.avif',
        altText: 'Dove Original Beauty Bar Soap 16 Pack Box',
        isPrimary: true,
      },
    ],
    inStock: true,
    stockQuantity: 40,
    ratingAverage: 4.9,
    reviewCount: 530,
    specifications: [
      { label: 'Count', value: '16 Bars' },
      { label: 'Net Weight', value: '60 oz Total (16 x 3.75 oz / 106g)' },
      { label: 'Formula', value: '1/4 Moisturizing Cream, Sulfate-Free' },
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-011',
    slug: 'cetaphil-moisturizing-lotion-2pack',
    gtin: '302993910202',
    name: 'Cetaphil Moisturizing Lotion',
    brand: 'Cetaphil',
    categorySlug: 'personal-care',
    subCategorySlug: 'lotions',
    description: 'light weight lotion hydrates for 48 hours leaving skin soft and smooth for normal & dry skin',
    price: 5400,
    currency: 'BIRR',
    images: [{ url: '/products/cetaphil-moisturizing-lotion-2pack.avif', altText: 'Cetaphil Moisturizing Lotion 2-Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 50,
    ratingAverage: 4.9,
    reviewCount: 410,
    specifications: [{ label: 'Volume', value: '40 fl oz Total (2 x 20 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-012',
    slug: 'cerave-facial-moisturizing-lotion-3pack',
    gtin: '360600053738',
    name: 'CeraVe Daily Moisturizing',
    brand: 'CeraVe',
    categorySlug: 'personal-care',
    subCategorySlug: 'lotions',
    description: 'Daily moisturizing lotion dor normal and dryskin helps restore protective skin barrier',
    price: 5900,
    currency: 'BIRR',
    images: [{ url: '/products/cerave-facial-moisturizing-lotion-3pack.png', altText: 'CeraVe Facial Moisturizing Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 30,
    ratingAverage: 4.8,
    reviewCount: 320,
    specifications: [{ label: 'Set Includes', value: 'Facial Lotion AM SPF 30 & PM Lotions' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-013',
    slug: 'old-spice-swagger-deodorant-4pack',
    gtin: '037000976521',
    name: 'Old Spice Swagger Aluminum-Free Deodorant',
    brand: 'Old Spice',
    categorySlug: 'personal-care',
    subCategorySlug: 'deodorant',
    description: "Men's deodorant ALUMINUM FREE PROTECTION SWAGGER TRANSFORMS THE UNFRESH INTO LEGENDS OF CONFIDENCE SCENT BOOSTED WITH ANTIOXIDANTS",
    price: 2100,
    currency: 'BIRR',
    images: [{ url: '/products/old-spice-4pack.avif', 
               altText: 'Old Spice Swagger Deodorant 4-Pack', 
               isPrimary: true }
            ],
    inStock: true,
    stockQuantity: 45,
    ratingAverage: 4.7,
    reviewCount: 195,
    specifications: [{ label: 'Weight', value: '12 oz Total (4 x 3.0 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-014',
    slug: 'olay-essential-botanicals-body-wash',
    gtin: '037000847164',
    name: 'Olay Essential Botanicals Body Wash',
    brand: 'Olay',
    categorySlug: 'personal-care',
    subCategorySlug: 'body-wash',
    description: 'BODY WASH INFUSED WITH ESSENTIAL OILS AND VITAMIN B3 COMPLEX FOR FRESH AND RADIANT SKIN LONG LASTING FRAGRANCE AVAILABLE WITH VARIETY OF SCENTS',
    price: 3600,
    currency: 'BIRR',
    images: [
      {
        url: '/products/olay-3-body- washes.jpg',
        altText: 'Olay Essential Botanicals Body Wash 3-Pack',
        isPrimary: true,
      },
    ],
    inStock: true,
    stockQuantity: 35,
    ratingAverage: 4.9,
    reviewCount: 168,
    specifications: [
      { label: 'Volume', value: '70.8 fl oz Total (3 x 23.6 fl oz / 700 mL)' },
      {
        label: 'Scents Included',
        value: 'Lavender Milk & Sandalwood, Spiced Chai & Pear, White Tea & Cucumber',
      },
      { label: 'Key Ingredient', value: 'Vitamin B3 Complex' },
    ],
    updatedAt: new Date().toISOString(),
  },

  // --- MATERIALS FROM THE STORE MATERIALS EXCEL SHEET (NON-DUPLICATE ITEMS) ---
  {
    id: 'prod-015',
    slug: 'colgate-total',
    gtin: '',
    name: 'Colgate Toothpaste',
    brand: 'Colgate',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Toothpaste for everyday dental hygiene total active protection anticavity, antigingivitis and antisensitivity',
    price: 1900,
    currency: 'BIRR',
    images: [{ url: '/products/colgate-total.avif', altText: 'Colgate Total', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2300' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-016',
    slug: 'gillette-ultimate-protection',
    gtin: '',
    name: 'Gillette Deodorant',
    brand: 'Gillette',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'ULTIMATE PROTECTION NON IRRITANT 72HR ANTIPERSPIRANT PROTECTION',
    price: 2100,
    currency: 'BIRR',
    images: [{ url: '/products/Gillette-Ultimate-Protection.jpg', altText: 'Gillette Ultimate Protection', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2900' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-017',
    slug: 'cheerios',
    gtin: '',
    name: 'Cheerios',
    brand: 'Cheerios',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Ready-to-eat toasted 100% whole-grain oat cereal',
    price: 2650,
    currency: 'BIRR',
    images: [{ url: '/products/Cheerios-Oats.jpg', altText: 'Cheerios', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000 old price' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-018',
    slug: 'krkland-organic-maple-syrup',
    gtin: '',
    name: 'Krkland Organic Maple Syrup',
    brand: 'Krkland',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'organic maple syrup 100% pure us grade A amber color rich taste',
    price: 5000,
    currency: 'BIRR',
    images: [{ url: '/products/Krkland-Organic-Maple-Syrup.jpg', altText: 'Krkland Organic Maple Syrup', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-019',
    slug: 'kirkland-organic-honey',
    gtin: '',
    name: 'Kirkland Organic Honey',
    brand: 'Kirkland',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'organic raw & unfiltered honey product of brazil',
    price: 2500,
    currency: 'BIRR',
    images: [{ url: '/products/Kirkland-Organic-Honey.jpg', altText: 'Kirkland Organic Honey', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-020',
    slug: 'dove-advanced-care-invisible',
    gtin: '',
    name: 'Dove Advanced Care Invisible',
    brand: 'Dove',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Deodorant ADVANCED CARE 72HR-INVISIBLE ANTIPERSPIRANT DEODORANT CUCUMBER AND CACTUS WATER',
    price: 2200,
    currency: 'BIRR',
    images: [{ url: '/products/Dove-Advanced-Care-Invisible.avif', altText: 'Dove Advanced Care Invisible', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2400' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-021',
    slug: 'dove-intensive-repair',
    gtin: '',
    name: 'Dove Shampoo',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'INTENSIVE REPAIR SHAMPOO DAMAGE THERAPY  BIO PROTEIN CARE +AMINO SERUM STOP 98% OF VISIBLE DAMAGE ,BREAKAGE , SYSTEM VS NON CONDITIONING SHAMPOO',
    price: 4200,
    currency: 'BIRR',
    images: [{ url: '/products/Dove-Intensive-Repair.avif', altText: 'Dove Intensive Repair', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '4500-5000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-022',
    slug: 'jif-creamy-peanut-butter',
    gtin: '',
    name: 'Jif Creamy Peanut Butter',
    brand: 'Jif',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Peanut butter spread made from roasted peanuts.',
    price: 3400,
    currency: 'BIRR',
    images: [{ url: '/products/Jif-Creamy-Peanut-Butter.jpg', altText: 'Jif Creamy Peanut Butter', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2500-4000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-023',
    slug: 'cinnamon-toast-crunch',
    gtin: '',
    name: 'Cinnamon Toast Crunch',
    brand: 'Cinnamon',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Crispy, Sweetened whole wheat and rice cereal flavored with cinnamon',
    price: 3500,
    currency: 'BIRR',
    images: [{ url: '/products/Cinnamon-Toast-Crunch.jpg', altText: 'Cinnamon Toast Crunch', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '4000-4900' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-024',
    slug: 'tresemme shampoo',
    gtin: '',
    name: 'tresemme shampoo',
    brand: 'Tresemme',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Hair-care product ULTIMATE MOISTURE 72HRS HYDRATION SMOOTHNESS & SHINE HEAT PROTECTION',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/Tresemme-Hydration-Smoothness-and-Shine.jpg', altText: 'Tresemme Hydration Smoothness and Shine', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '8000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-025',
    slug: 'aveeno-daily-moisturizing-lotion',
    gtin: '',
    name: 'Aveeno Daily Moisturizing Lotion',
    brand: 'Aveeno',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Daily moisturizing lotion fragrance free normal-dry/sensitive skin instantly strengthens the skin barrier with 48 hrs hydration',
    price: 4300,
    currency: 'BIRR',
    images: [{ url: '/products/Aveeno-Daily-Moisturizing-Lotion.jpg', altText: 'Aveeno Daily Moisturizing Lotion', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '5000-5500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-026',
    slug: 'sensodyne-sensitivity-protection',
    gtin: '',
    name: 'sensodnye toothpaste',
    brand: 'Sensodyne',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Toothpaste formulated for sensitive teeth and cavity prevention 24/7 sensitivity protection + strong & healthy teeth',
    price: 2700,
    currency: 'BIRR',
    images: [{ url: '/products/Sensodyne-Sensitivity-Protection.jpg', altText: 'Sensodyne Sensitivity Protection', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2500-3300' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-027',
    slug: 'crest-pro-health-advanced',
    gtin: '',
    name: 'Crest Pro-Health Advanced',
    brand: 'Crest',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Multi-benefit toothpaste for oral hygiene and protection. 24 hour anti-bac protection whitening + intensive clean',
    price: 2000,
    currency: 'BIRR',
    images: [{ url: '/products/Crest-Pro-Health-Advanced.avif', altText: 'Crest Pro-Health Advanced', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-028',
    slug: 'irish-spring',
    gtin: '',
    name: 'Irish Spring',
    brand: 'Irish',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Irish Spring',
    price: 470,
    currency: 'BIRR',
    images: [{ url: '/products/Irish-Spring.jpg', altText: 'Irish Spring', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '500-700' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-029',
    slug: 'kirkland-pistachios',
    gtin: '',
    name: 'Salted Pistachios',
    brand: 'Kirkland',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'us#1 naturally opened roasted and salted pistachios',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/Kirkland-Pistachios.jpg', altText: 'Kirkland Pistachios', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '6000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-030',
    slug: 'trident',
    gtin: '',
    name: 'Trident',
    brand: 'Trident',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'trident refreshingly long lasting tropical twist, watermelon twist, island berry lime',
    price: 480,
    currency: 'BIRR',
    images: [{ url: '/products/Trident-gum.jpg', altText: 'Trident', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-031',
    slug: 'degree-deodorant',
    gtin: '',
    name: 'Degree Deodorant',
    brand: 'Degree',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Deodorant/antiperspirant FOR MEN designed for odor and sweat protection.',
    price: 2000,
    currency: 'BIRR',
    images: [{ url: '/products/Degree-Deodorant.avif', altText: 'Degree Deodorant', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2300' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-032',
    slug: 'extra-long-lasting-flavor',
    gtin: '',
    name: 'Extra Long Lasting Flavor',
    brand: 'Extra',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Chewing gum; mint flavour 18packs 15 sticks per pack',
    price: 480,
    currency: 'BIRR',
    images: [{ url: '/products/Extra-Long-Lasting-Flavor.jpg', altText: 'Extra Long Lasting Flavor', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-033',
    slug: 'oreo',
    gtin: '',
    name: 'Oreo',
    brand: 'Oreo',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Oreo',
    price: 1000,
    currency: 'BIRR',
    images: [{ url: '/products/Oreo-biscuts.jpg', altText: 'Oreo', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '1000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-034',
    slug: 'dove-deep-moisture',
    gtin: '',
    name: 'Dove Deep Moisture',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'BODY LOTION UNVEIL SOFTER, RADIANT SKIN WITH CREAMY LATHER AND THE ORIGINAL',
    price: 3400,
    currency: 'BIRR',
    images: [{ url: '/products/Dove-Deep-Moisture.avif', altText: 'Dove Deep Moisture', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '4000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-038',
    slug: 'one-a-day-womans-complete-multi-vitamin',
    gtin: '',
    name: 'One A Day Womans Complete Multi-vitamin',
    brand: 'One',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: "Daily multivitamin WOMEN'S complete multivitamin supplement key nutrients including VITAMINS A, C, D, & E VITAMINS B6 & B12 BIOTIN, IRON",
    price: 6800,
    currency: 'BIRR',
    images: [{ url: '/products/One-A-Day-Womans-Complete-Multi-vitamin.avif', altText: 'One A Day Womans Complete Multi-vitamin', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '6500-7500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-039',
    slug: 'nature-made-prenatal',
    gtin: '',
    name: 'Nature Made Prenatal',
    brand: 'Nature',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: "Multivitamin with 20 key nutrients, supplement formulated for pregnancy, Clinically Proven Absorption of Folic Acid & Iron, supports the development of baby's brain, eyes & nervous system",
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/Nature-Made-Prenatal.avif', altText: 'Nature Made Prenatal', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '7500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-040',
    slug: 'heinz-tomato-ketchup',
    gtin: '',
    name: 'Heinz Tomato Ketchup',
    brand: 'Heinz',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'TOMATO KETCHUP GROWN NOT MADE NO ARTIFICIAL FLAVORS, PRESERVATIVES OR COLORS',
    price: 2800,
    currency: 'BIRR',
    images: [{ url: '/products/Heinz-Tomato-Ketchup.jpg', altText: 'Heinz Tomato Ketchup', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2500-2800' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-041',
    slug: 'sc-johnson-ziplock',
    gtin: '',
    name: 'Sc Johnson Ziplock',
    brand: 'Sc',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'scjohnson resealable multi purpose storage bags and household food-storage',
    price: 2100,
    currency: 'BIRR',
    images: [{ url: '/products/Sc-Johnson-Ziplock.jpg', altText: 'Sc Johnson Ziplock', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-042',
    slug: 'nutella-peanut',
    gtin: '',
    name: 'Nutella Peanut',
    brand: 'Nutella',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Peanut-flavored chocolate/nut spread.',
    price: 3500,
    currency: 'BIRR',
    images: [{ url: '/products/Nutella-Peanut.jpg', altText: 'Nutella Peanut', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-043',
    slug: 'shin-raymun',
    gtin: '',
    name: 'Shin Raymun',
    brand: 'Shin',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Korean instant noodle product with spicy flavor.',
    price: 490,
    currency: 'BIRR',
    images: [{ url: '/products/Shin-Raymun.jpg', altText: 'Shin Raymun', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-044',
    slug: 'febreze-air-freshner',
    gtin: '',
    name: 'Febreze Air Freshner',
    brand: 'Febreze',
    categorySlug: 'home-care',
    subCategorySlug: 'air-fresheners',
    description: 'Home fragrance and odor-eliminating air mist with variety of scents',
    price: 1100,
    currency: 'BIRR',
    images: [{ url: '/products/Febreze-Air-Freshner.jpg', altText: 'Febreze Air Freshner', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-045',
    slug: 'desitin-maximum-strength-paste',
    gtin: '',
    name: 'Desitin Maximum Strength Paste',
    brand: 'Desitin',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'smooth, daily barrier cream to prevent routine diaper rash maximum level skin protectant treatment and prevention of diaper rash, sealing out wetness and soothing chafed skin',
    price: 3000,
    currency: 'BIRR',
    images: [{ url: '/products/Desitin-Maximum-Strength-Paste.jpg', altText: 'Desitin Maximum Strength Paste', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-046',
    slug: 'colgate-individually-sealed-brushes',
    gtin: '',
    name: 'Colgate Individually Sealed Brushes',
    brand: 'Colgate',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Manual toothbrush for daily oral cleaning. Fights root cause of oral care problems',
    price: 500,
    currency: 'BIRR',
    images: [{ url: '/products/Colgate-Individually-Sealed-Brushes.jpg', altText: 'Colgate Individually Sealed Brushes', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-047',
    slug: 'blush-cardigen-fine-fregrance-mist',
    gtin: '',
    name: 'Blush Cardigen Fine Fregrance Mist',
    brand: 'Blush',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: "Women's body fragrance mist with variety of scent options",
    price: 3900,
    currency: 'BIRR',
    images: [{ url: '/products/Blush-Cardigen-Fine-Fregrance Mist.webp', altText: 'Blush Cardigen Fine Fregrance Mist', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
  id: 'prod-048',
  slug: 'ferrero-collection-48pcs',
  gtin: '',
  name: 'Ferrero Collection 48 pcs',
  brand: 'Ferrero',
  categorySlug: 'pantry',
  subCategorySlug: 'confectionery',
  description: 'Assortment of individually wrapped Ferrero chocolates',
  price: 6800,
  currency: 'BIRR',
  images: [{ url: '/products/Ferrero-Collection-48pcs.jpg', altText: 'Ferrero Collection 48 pcs', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '6800' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-049',
  slug: 'bouchard-dark-belgian-chocolate',
  gtin: '',
  name: 'Bouchard Dark Belgian Chocolate',
  brand: 'Bouchard',
  categorySlug: 'pantry',
  subCategorySlug: 'confectionery',
  description: 'Belgian dark chocolate bar',
  price: 6500,
  currency: 'BIRR',
  images: [{ url: '/products/Bouchard-Dark-Belgian-Chocolate.jpg', altText: 'Bouchard Dark Belgian Chocolate', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '6500' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-050',
  slug: 'nutty-fruity-dubai-chocolate-bars',
  gtin: '',
  name: 'Nutty Fruity Dubai Chocolate Bars',
  brand: 'Nutty Fruity',
  categorySlug: 'pantry',
  subCategorySlug: 'confectionery',
  description: 'Chocolate bars inspired by Dubai-style chocolate, typically containing a nutty/crispy filling',
  price: 4550,
  currency: 'BIRR',
  images: [{ url: '/products/Nutty-Fruity-Dubai-Chocolate-Bars.jpg', altText: 'Nutty Fruity Dubai Chocolate Bars', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '4550' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-051',
  slug: 'godiva-milk-chocolate',
  gtin: '',
  name: 'Godiva Milk Chocolate',
  brand: 'Godiva',
  categorySlug: 'pantry',
  subCategorySlug: 'confectionery',
  description: 'Premium milk chocolate confectionery',
  price: 4450,
  currency: 'BIRR',
  images: [{ url: '/products/Godiva-Milk-Chocolate.jpg', altText: 'Godiva Milk Chocolate', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '4450' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-052',
  slug: 'youtheory-ashwagandha',
  gtin: '',
  name: 'Ashwagandha',
  brand: 'Youtheory',
  categorySlug: 'supplements',
  subCategorySlug: 'herbal',
  description: 'daily adaptogen formula dietary supplement, supports a healthy stress response',
  price: 6800,
  currency: 'BIRR',
  images: [{ url: '/products/Youtheory-Ashwagandha.avif', altText: 'Ashwagandha', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '6800' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-053',
  slug: 'natures-bounty-magnesium-glycinate',
  gtin: '',
  name: 'Magnesium Glycinate',
  brand: "Nature's Bounty",
  categorySlug: 'supplements',
  subCategorySlug: 'minerals',
  description: 'High Absorption Magnesium Glycinate Supports Muscle Relaxation, Bone, heart and Nerve Health',
  price: 6000,
  currency: 'BIRR',
  images: [{ url: '/products/Natures-Bounty-Magnesium-Glycinate.jpg', altText: 'Magnesium Glycinate', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '6000' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-054',
  slug: 'trident-fruit',
  gtin: '',
  name: 'Trident Fruit',
  brand: 'Trident',
  categorySlug: 'pantry',
  subCategorySlug: 'chewing-gum',
  description: 'trident refreshingly long lasting tropical twist, watermelon twist, island berry lime',
  price: 480,
  currency: 'BIRR',
  images: [{ url: '/products/Trident-Fruit.jpg', altText: 'Trident Fruit', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '480' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-055',
  slug: 'kirkland-cashews',
  gtin: '',
  name: 'Cashews',
  brand: 'Kirkland Signature',
  categorySlug: 'pantry',
  subCategorySlug: 'nuts-seeds',
  description: 'fancy whole cashews with seasalt',
  price: 6000,
  currency: 'BIRR',
  images: [{ url: '/products/Kirkland-Cashews.jpg', altText: 'Cashews', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '6000' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-056',
  slug: 'kirkland-almonds',
  gtin: '',
  name: 'Almonds',
  brand: 'Kirkland Signature',
  categorySlug: 'pantry',
  subCategorySlug: 'nuts-seeds',
  description: 'us#1 supreme whole steam pasteurized almonds',
  price: 4900,
  currency: 'BIRR',
  images: [{ url: '/products/Kirkland-Almonds.jpg', altText: 'Almonds', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '4900' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-057',
  slug: 'kirkland-unsalted-pistachios',
  gtin: '',
  name: 'Unsalted Pistachios',
  brand: 'Kirkland Signature',
  categorySlug: 'pantry',
  subCategorySlug: 'nuts-seeds',
  description: 'roasted and unsalted pistachios with shell',
  price: 6000,
  currency: 'BIRR',
  images: [{ url: '/products/Kirkland-Unsalted-Pistachios.jpg', altText: 'Unsalted Pistachios', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '6000' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-058',
  slug: 'kirkland-quinoa',
  gtin: '',
  name: 'Quinoa',
  brand: 'Kirkland Signature',
  categorySlug: 'pantry',
  subCategorySlug: 'grains-seeds',
  description: 'Edible quinoa grain glutenfree used as a food ingredient or side dish',
  price: 7000,
  currency: 'BIRR',
  images: [{ url: '/products/Kirkland-Quinoa.jpg', altText: 'Quinoa', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '7000' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-059',
  slug: 'kirkland-almond-butter',
  gtin: '',
  name: 'Almond Butter',
  brand: 'Kirkland Signature',
  categorySlug: 'pantry',
  subCategorySlug: 'nut-butter',
  description: 'creamy almond butter',
  price: 3800,
  currency: 'BIRR',
  images: [{ url: '/products/Kirkland-Almond-Butter.jpg', altText: 'Almond Butter', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3800' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-060',
  slug: 'sweet-baby-rays-barbecue-sauce',
  gtin: '',
  name: 'Barbecue Sauce',
  brand: "Sweet Baby Ray's",
  categorySlug: 'pantry',
  subCategorySlug: 'sauces-condiments',
  description: 'Savory-sweet sauce commonly used with grilled or roasted foods.',
  price: 3800,
  currency: 'BIRR',
  images: [{ url: '/products/Sweet-Baby-Rays-Barbecue-Sauce.jpg', altText: 'Barbecue Sauce', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3800' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-061',
  slug: 'graza-extra-virgin-olive-oil',
  gtin: '',
  name: 'Extra Virgin Olive Oil',
  brand: 'Graza',
  categorySlug: 'pantry',
  subCategorySlug: 'cooking-oils',
  description: 'Extra virgin olive oil NO BLENDING, NO FUNNY BUSINESS, JUST 100% PURE PICUAL OLIVE OIL FROM JAEN,SPAIN',
  price: 3500,
  currency: 'BIRR',
  images: [{ url: '/products/Graza-Extra-Virgin-Olive-Oil.jpg', altText: 'Extra Virgin Olive Oil', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3500' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-062',
  slug: 'dove-conditioner',
  gtin: '',
  name: 'Dove Conditioner',
  brand: 'Dove',
  categorySlug: 'personal-care',
  subCategorySlug: 'hair-care',
  description: 'DOVE INTENSIVE REPAIR DAMAGE THERAPY BIO PROTEIN CARE + AMINO SERUM IT PROTECTS, REPAIRS AND RESTORES HAIR TO REDUCE SIGNS OF DAMAGE',
  price: 4200,
  currency: 'BIRR',
  images: [{ url: '/products/Dove-Conditioner.jpg', altText: 'Dove Conditioner', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '4200' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-063',
  slug: 'nexxus-shampoo',
  gtin: '',
  name: 'Nexxus Shampoo',
  brand: 'Nexxus',
  categorySlug: 'personal-care',
  subCategorySlug: 'hair-care',
  description: 'Hair shampoo formulated for advanced hydration for dry & brittle',
  price: 4500,
  currency: 'BIRR',
  images: [{ url: '/products/Nexxus-Shampoo.jpg', altText: 'Nexxus Shampoo', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '4500' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-064',
  slug: 'nexxus-conditioner',
  gtin: '',
  name: 'Nexxus Conditioner',
  brand: 'Nexxus',
  categorySlug: 'personal-care',
  subCategorySlug: 'hair-care',
  description: 'Hair conditioner formulated for advanced hydration',
  price: 4500,
  currency: 'BIRR',
  images: [{ url: '/products/Nexxus-Conditioner.jpg', altText: 'Nexxus Conditioner', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '4500' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-065',
  slug: 'tresemme-conditioner',
  gtin: '',
  name: 'TRESemmé Conditioner',
  brand: 'TRESemmé',
  categorySlug: 'personal-care',
  subCategorySlug: 'hair-care',
  description: 'ultimate moisture conditioner creates your desire look with long lasting smoothness and brilliant shine from our ultimate moisture system 72 hrs hydration smoothness & shine',
  price: 4000,
  currency: 'BIRR',
  images: [{ url: '/products/TRESemme-Conditioner.jpg', altText: 'TRESemmé Conditioner', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '4000' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-066',
  slug: 'head-and-shoulders-shampoo',
  gtin: '',
  name: 'Head & Shoulders Shampoo',
  brand: 'Head & Shoulders',
  categorySlug: 'personal-care',
  subCategorySlug: 'hair-care',
  description: '2 IN 1 ANTI-dandruff shampoo for scalp and hair CLEANSING WITH ALOEVERA, COCONUT WATER & VITAMINS E, B3',
  price: 6900,
  currency: 'BIRR',
  images: [{ url: '/products/Head-and-Shoulders-Shampoo.jpg', altText: 'Head & Shoulders Shampoo', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '6900' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-067',
  slug: 'crest-3d-white',
  gtin: '',
  name: 'Crest 3D White',
  brand: 'Crest',
  categorySlug: 'personal-care',
  subCategorySlug: 'oral-care',
  description: 'Whitening toothpaste; brilliant mint',
  price: 2000,
  currency: 'BIRR',
  images: [{ url: '/products/Crest-3D-White.jpg', altText: 'Crest 3D White', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '2000' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-068',
  slug: 'cerave-spf30',
  gtin: '',
  name: 'CeraVe SPF30',
  brand: 'CeraVe',
  categorySlug: 'personal-care',
  subCategorySlug: 'sun-care',
  description: 'CeraVe oilfree facial moisturizing lotion with sunscreen moisturizes throughout the day & helps restore the protective skin barrier',
  price: 3900,
  currency: 'BIRR',
  images: [{ url: '/products/CeraVe-SPF30.jpg', altText: 'CeraVe SPF30', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3900' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-069',
  slug: 'eos-body-lotion',
  gtin: '',
  name: 'EOS Body Lotion',
  brand: 'eos',
  categorySlug: 'personal-care',
  subCategorySlug: 'skin-care',
  description: 'shea better 24h moisture body lotion 7 nourishing oils + butters soothing protection for dry skin',
  price: 4000,
  currency: 'BIRR',
  images: [{ url: '/products/EOS-Body-Lotion.jpg', altText: 'EOS Body Lotion', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '4000' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-070',
  slug: 'tree-hut-body-scrub',
  gtin: '',
  name: 'Tree Hut Body Scrub',
  brand: 'Tree Hut',
  categorySlug: 'personal-care',
  subCategorySlug: 'skin-care',
  description: 'Exfoliating body scrub for smoothing and cleansing the skin. Soothe + renew, variety type with different scent',
  price: 4000,
  currency: 'BIRR',
  images: [{ url: '/products/Tree-Hut-Body-Scrub.jpg', altText: 'Tree Hut Body Scrub', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '4000' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-071',
  slug: 'shine-n-jam-extra-hold-gel',
  gtin: '',
  name: "Shine 'n Jam Extra Hold Gel",
  brand: "Shine 'n Jam",
  categorySlug: 'personal-care',
  subCategorySlug: 'hair-styling',
  description: 'Extra-hold conditioning and styling gel with honey extract',
  price: 2900,
  currency: 'BIRR',
  images: [{ url: '/products/Shine-n-Jam-Extra-Hold-Gel.jpg', altText: "Shine 'n Jam Extra Hold Gel", isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '2900' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-072',
  slug: 'mielle-rosemary-mint',
  gtin: '',
  name: 'Mielle Rosemary',
  brand: 'Mielle',
  categorySlug: 'personal-care',
  subCategorySlug: 'hair-care',
  description: 'Rosemary-based hair-care product scalp & hair strengthening oil for daily use scalp treatment and split end care',
  price: 2400,
  currency: 'BIRR',
  images: [{ url: '/products/Mielle-Rosemary.jpg', altText: 'Mielle Rosemary', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '2400' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-073',
  slug: 'shin-ramyun',
  gtin: '',
  name: 'Shin Ramyun',
  brand: 'Nongshim',
  categorySlug: 'pantry',
  subCategorySlug: 'instant-noodles',
  description: 'Korean instant noodle product with spicy flavor.',
  price: 490,
  currency: 'BIRR',
  images: [{ url: '/products/Shin-Ramyun.jpg', altText: 'Shin Ramyun', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '490' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-074',
  slug: 'bath-and-body-works-body-lotion-women',
  gtin: '',
  name: 'Bath & Body Works Body Lotion Women',
  brand: 'Bath & Body Works',
  categorySlug: 'personal-care',
  subCategorySlug: 'skin-care',
  description: 'Women\'s body lotion for daily nourishing with shea butter + coconut oil 24 hour moisture with variety of scent options',
  price: 3800,
  currency: 'BIRR',
  
  images: [{ url: '/products/Bath-and-Body-Works-Fragrance-Mist-Women.jpg', altText: 'Bath & Body Works Body Lotion Women', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3800' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-075',
  slug: 'bath-and-body-works-fragrance-mist-women',
  gtin: '',
  name: 'Bath & Body Works Fragrance Mist Women',
  brand: 'Bath & Body Works',
  categorySlug: 'personal-care',
  subCategorySlug: 'fragrance',
  description: 'Women\'s body fragrance mist with variety of scent options',
  price: 3900,
  currency: 'BIRR',
  images: [{ url: '/products/Bath-and-Body-Works-Body-Lotion-Women.jpg', altText: 'Bath & Body Works Fragrance Mist Women', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3900' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-076',
  slug: 'bath-and-body-works-mens-body-spray',
  gtin: '',
  name: "Bath & Body Works Men's Body Spray",
  brand: 'Bath & Body Works',
  categorySlug: 'personal-care',
  subCategorySlug: 'fragrance',
  description: "Men's body fragrance deodorizing spray 24hour odor protection variety scent options",
  price: 3850,
  currency: 'BIRR',
  images: [{ url: '/products/Bath-and-Body-Works-Mens-Body-Spray.jpg', altText: "Bath & Body Works Men's Body Spray", isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3850' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-077',
  slug: 'bath-and-body-works-shower-gel',
  gtin: '',
  name: 'Bath & Body Works Shower Gel',
  brand: 'Bath & Body Works',
  categorySlug: 'personal-care',
  subCategorySlug: 'bath-body',
  description: 'Shower gel/body wash with pro vitamins B5 + aloe',
  price: 3850,
  currency: 'BIRR',
  images: [{ url: '/products/Bath-and-Body-Works-Shower-Gel.jpg', altText: 'Bath & Body Works Shower Gel', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3850' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-078',
  slug: 'goya-adobo-all-purpose-seasoning',
  gtin: '',
  name: 'Goya Adobo All Purpose Seasoning',
  brand: 'Goya',
  categorySlug: 'pantry',
  subCategorySlug: 'seasonings-spices',
  description: 'All-purpose seasoning blend used to flavor meat, poultry, seafood and other foods.',
  price: 3100,
  currency: 'BIRR',
  images: [{ url: '/products/Goya-Adobo-All-Purpose-Seasoning.jpg', altText: 'Goya Adobo All Purpose Seasoning', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3100' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-079',
  slug: 'badia-all-purpose-seasoning',
  gtin: '',
  name: 'Badia All Purpose Seasoning',
  brand: 'Badia',
  categorySlug: 'pantry',
  subCategorySlug: 'seasonings-spices',
  description: 'All-purpose seasoning blend for cooking and food preparation.',
  price: 2950,
  currency: 'BIRR',
  images: [{ url: '/products/Badia-All-Purpose-Seasoning.jpg', altText: 'Badia All Purpose Seasoning', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '2950' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-080',
  slug: 'big-bold-chicken-sweet-spicy-tangy-seasoning',
  gtin: '',
  name: 'Big Bold Chicken Sweet Spicy Tangy Seasoning',
  brand: 'Big Bold',
  categorySlug: 'pantry',
  subCategorySlug: 'seasonings-spices',
  description: 'Sweet, spicy and tangy seasoning intended for chicken and other foods.',
  price: 2700,
  currency: 'BIRR',
  images: [{ url: '/products/Big-Bold-Chicken-Sweet-Spicy-Tangy-Seasoning.jpg', altText: 'Big Bold Chicken Sweet Spicy Tangy Seasoning', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '2700' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-081',
  slug: 'vita-c-foam-cleanser',
  gtin: '',
  name: 'Vita C Foam Cleanser',
  brand: 'Dearboo',
  categorySlug: 'personal-care',
  subCategorySlug: 'skin-care',
  description: 'dark spot care to brightens the skin, evens out blotchy tone, hydrate leaving your skin feeling refreshed and renewed every day',
  price: 3200,
  currency: 'BIRR',
  images: [{ url: '/products/Vita-C-Foam-Cleanser.jpg', altText: 'Vita C Foam Cleanser', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3200' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-082',
  slug: 'cleansing-foam-hyaluronic-acid',
  gtin: '',
  name: 'Cleansing Foam Hyaluronic Acid',
  brand: 'Softymo',
  categorySlug: 'personal-care',
  subCategorySlug: 'skin-care',
  description: 'japanese 2 in 1 facial cleanser and makeup remover cleans deep seated pore impurities without stripping natural moisture skin feeling soft, bouncy, and refreshed',
  price: 2400,
  currency: 'BIRR',
  images: [{ url: '/products/Cleansing-Foam-Hyaluronic-Acid.jpg', altText: 'Cleansing Foam Hyaluronic Acid', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '2400' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-083',
  slug: 'snail-toner',
  gtin: '',
  name: 'Snail Toner',
  brand: 'Dearboo',
  categorySlug: 'personal-care',
  subCategorySlug: 'skin-care',
  description: 'light weight, hydrating korean skincare toner designed to prep the skin, improve dullness, promote radiant, glassy complexion',
  price: 2800,
  currency: 'BIRR',
  images: [{ url: '/products/Snail-Toner.jpg', altText: 'Snail Toner', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '2800' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-084',
  slug: 'vita-c-toner',
  gtin: '',
  name: 'Vita C Toner',
  brand: 'Dearboo',
  categorySlug: 'personal-care',
  subCategorySlug: 'skin-care',
  description: 'korean facial skin care toner for dark spot correction, firming, brightening and hydration',
  price: 3000,
  currency: 'BIRR',
  images: [{ url: '/products/Vita-C-Toner.jpg', altText: 'Vita C Toner', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '3000' }],
  updatedAt: new Date().toISOString(),
},
{
  id: 'prod-085',
  slug: 'glass-skin-snail-serum',
  gtin: '',
  name: 'Glass Skin Snail Serum',
  brand: 'Dearboo',
  categorySlug: 'personal-care',
  subCategorySlug: 'skin-care',
  description: 'a korean product which is light weight, hydrating facial treatment designed to soothe, plump and give the skin a radiant, dewy finish also helps absorb deep nutrients, smooths texture and supports skin regeneration',
  price: 2900,
  currency: 'BIRR',
  images: [{ url: '/products/Glass-Skin-Snail-Serum.jpg', altText: 'Glass Skin Snail Serum', isPrimary: true }],
  inStock: false,
  stockQuantity: 0,
  ratingAverage: 0,
  reviewCount: 0,
  specifications: [{ label: 'Source Price', value: '2900' }],
  updatedAt: new Date().toISOString(),
},
];

export async function getProductBySlug(slug: string): Promise<Product | null> {
  return MOCK_PRODUCTS.find((p) => p.slug === slug) || null;
}
